<template>
  <div class="bg-white rounded p-5 mt-5">
    <span
      class="flex border-b-2 w-full font-semibold text-xl text-primary py-2 mx-auto"
    >
      {{ allaction }} Group
    </span>
    <div class="w-full h-screen overflow-y-auto">
      <form class="mt-5 w-full pr-3" @submit.prevent="submit">
        <div>
          <accordion-component title="Basic info" v-model="opened">
            <template v-slot:misc>
              <info></info>
            </template>
            <template v-slot:default>
              <div class="w-full grid grid-cols-2 gap-4 mt-5">
                <cornie-input label="Group ID" placeholder="--Autogenerated--" disabled />
                <cornie-select
                  :onChange="setValue(options.text)"
                  :items="items"
                  :rules="required"
                  v-model="status"
                  label="Status"
                  placeholder="Draft"
                  disabled
                >
                </cornie-select>
                <fhir-input
                  reference="http://hl7.org/fhir/ValueSet/group-type"
                  class="w-full"
                  :rules="required"
                  v-model="type"
                  label="Type"
                  placeholder="--Select--"
                />
                <cornie-select
                  :rules="required"
                  :items="['state']"
                  v-model="state"
                  label="State"
                  placeholder="--Select--"
                >
                </cornie-select>
                <cornie-input
                  label="Name"
                  placeholder="--Enter--"
                  v-model="name"
                />
                <cornie-input
                  label="Code"
                  placeholder="--Enter--"
                  v-model="code"
                  required
                />
                <cornie-input
                  label="Members"
                  placeholder="--Enter--"
                  v-model="quantity"
                  disabled
                />
                <cornie-select
                  :rules="required"
                  :items="[
                    'Practitioner',
                    'Patient',
                    'Practitioner Role',
                    'Device',
                    'Medication',
                  ]"
                  v-model="managingEntity"
                  disabled
                  label="Managing Entity"
                  placeholder="--Select--"
                ></cornie-select>
              </div>
            </template>
          </accordion-component>
          <accordion-component title="Qualification">
            <template v-slot:misc>
              <info></info>
            </template>
            <template v-slot:default>
              <div v-if="actorsList.length" class="grid grid-cols-12 mt-5">
                <div
                  class="flex justify-between col-span-4 pr-5"
                  :class="[
                    index !== actorsList.length - 1
                      ? 'border-r border-gray-400'
                      : '',
                    index % 2 !== 0 ? 'pl-5' : '',
                    index === actorsList.length - 1 ? 'pl-5' : '',
                  ]"
                  v-for="(actor, index) in actorsList"
                  :key="actor.id"
                >
                  <div class="flex justify-center items-center">
                    <div class="h-12 w-12 rounded-full overflow-hidden mr-1">
                      <img
                        :src="actor.image || '@/assets/img/avatar.svg'"
                        class="h-full w-full"
                        v-if="actor.type === 'Practitioner'"
                      />
                      <div
                        class="h-full w-full rounded-full overflow-hidden flex items-center justify-center bg-blue-500 text-white-cotton-ball font-bold"
                        v-else
                      >
                        {{ actor.name.substr(0, 2).toUpperCase() }}
                      </div>
                    </div>
                    <div class="flex flex-col items-start">
                      <div class="mb-0 font-bold text-sm">
                        <div class="flex justify-center items-center">
                          <div class="mr-1">
                            {{ actor.name }}
                          </div>
                          <div
                            class="font-bolder text-gray-400 mr-1"
                            v-if="actor.job"
                          >
                            •
                          </div>
                          <div class="text-xs text-gray-400">
                            {{ actor.job }}
                          </div>
                        </div>
                      </div>
                      <div class="text-xs text-gray-400">{{ actor.type }}</div>
                    </div>
                  </div>
                  <div class="flex justify-center items-center">
                    <button
                      class="border-0"
                      type="button"
                      @click="deleteMember(actor.id)"
                    >
                      <delete-icon />
                    </button>
                  </div>
                </div>
              </div>
              <add-actor
                @update-actors-list="updateActorsList"
                :memberToDelete="memberToDelete"
                @memberDeleted="memberToDelete = ''"
                type="button"
              />
            </template>
          </accordion-component>
        </div>
        <span class="flex justify-end w-full pb-96">
          <button
            @click="$router.push('/dashboard/provider/settings/group')"
            type="button"
            class="border border-primary rounded-md text-black mt-5 mr-3 py-2 px-8 focus:outline-none hover:bg-primary hover:text-white"
          >
            Cancel
          </button>

          <cornie-btn
            :loading="loading"
            type="submit"
            class="bg-danger rounded-md text-white mt-5 px-3 focus:outline-none hover:opacity-90"
          >
            Save
          </cornie-btn>
        </span>
      </form>
    </div>
  </div>
</template>
<script lang="ts">
import { Options, Vue } from "vue-class-component";
import AccordionComponent from "@/components/accordion-extended-component.vue";
import CornieInput from "@/components/cornieinput.vue";
import CornieSelect from "@/components/cornieselect.vue";
import CornieSelectQuestion from "@/components/cornieselect-question.vue";
import Textarea from "@/components/textarea.vue";
import PhoneInput from "@/components/phone-input.vue";
//import IGroup , { GroupMembers } from "@/types/IGroup";
import IGroup from "@/types/IGroup";
import { cornieClient } from "@/plugins/http";
import { namespace } from "vuex-class";
import { string } from "yup";
import { Prop, Watch } from "vue-property-decorator";
import OrgSelect from "@/components/orgSelect.vue";
import ColumnFilter from "@/components/columnfilter.vue";
import DEdit from "@/components/icons/dedit.vue";
import CDelete from "@/components/icons/cdelete.vue";
import CAdd from "@/components/icons/cadd.vue";
import AddIcon from "@/components/icons/add.vue";
import DatePicker from "@/components/daterangepicker.vue";
import SingleDatePicker from "./datepicker.vue";
import Period from "@/types/IPeriod";
import Info from "@/components/icons/info-blue-bg.vue";
import Avatar from "@/components/avatar.vue";
import EditIcon from "@/components/icons/edit-purple.vue";
import DeleteIcon from "@/components/icons/delete-red.vue";
import FhirInput from "@/components/fhir-input.vue";
import AddActor from "./components/AddActor.vue";

const group = namespace("group");
const dropdown = namespace("dropdown");

// const emptyMember: GroupMembers = {
//   name: "",
//   type: "",
// };

@Options({
  components: {
    CornieInput,
    CornieSelect,
    CornieSelectQuestion,
    OrgSelect,
    ColumnFilter,
    SingleDatePicker,
    Textarea,
    DEdit,
    CDelete,
    CAdd,
    AddIcon,
    PhoneInput,
    DatePicker,
    AccordionComponent,
    Info,
    FhirInput,
    Avatar,
    EditIcon,
    DeleteIcon,
    AddActor,
  },
})
export default class AddGroup extends Vue {
  @Prop({ type: String, default: "" })
  id!: string;

  @group.Action
  getGroupById!: (id: string) => IGroup;

  loading = false;
  expand = false;
  isVisible = "";
  opened = true;
  openedR = false;
  openedT = false;
  state = "";
  status = false;
  type = "";
  name = "";
  code = "";
  quantity = "";
  managingEntity = "";
  characteristicsCode = "";
  valueCodeableConcept = "";
  valueBoolean = "";
  valueQuantity = "";
  valueRange = "";
  valueRef = "";
  exclude = "";
  period = {} as Period;
  memberPeriod = "";
  // period: { start: "2011/12/15", end: "2017/12/19" };
  // memberPeriod: { start: "2011/12/15", end: "2017/12/19" };
  memberStatus = "";
  memberEntity = "--Select--";
  launchMemberdiag = false;
  aoption = "Active";
  // groupmember = { ...emptyMember };
  // groupmembers: GroupMembers[] = [];
  avatarSrc = "";
  show = false;
  options = [
    { text: "Active", value: true },
    { text: "Inactive", value: false },
  ];
  items = ["Active", "Inactive"];
  required = string().required();
  dropdowns = {} as IIndexableObject;
  @dropdown.Action
  getDropdowns!: (a: string) => Promise<IIndexableObject>;
  @Watch("id")
  idChanged() {
    this.setGroup();
  }
  async setGroup() {
    const group = await this.getGroupById(this.id);
    if (!group) return;

    this.state = group.state;
    this.status = group.status;
    this.type = group.type;
    this.name = group.name;
    this.code = group.code;
    this.quantity = group.quantity;
    this.managingEntity = group.managingEntity;
    this.actorsList = group.members;
  }
  get payload() {
    return {
      group: {
        state: this.state,
        status: this.status,
        type: this.type,
        name: this.name,
        code: this.code,
        quantity: this.quantity,
        managingEntity: this.managingEntity,
      },
      members: this.actorsList.map((item: any) => {
        return {
          userId: item.id,
          period: item.period,
          status: item.status,
        };
      }),
    };
  }
  get allaction() {
    return this.id ? "Edit" : "Add a";
  }

  actorsList = [] as any;
  memberToDelete = "" as string;

  async updateActorsList(actors: any) {
    this.actorsList = [actors[0], ...this.actorsList];

    this.memberEntity = "--Select--";
  }

  async deleteMember(id: string) {
    const confirm = await window.confirmAction({
      message: "Are you sure you want to remove practitioner?",
      title: "Remove Practitioner",
    });

    if (!confirm) return;

    this.actorsList = [
      ...this.actorsList.filter((item: any) => item.id !== id),
    ];

    this.memberToDelete = id;
  }

  async setValue(value: string) {
    if (value == "Active") {
      this.status = true;
    } else {
      this.status = false;
    }
  }

  async submit() {
    this.loading = true;
    if (this.id) await this.updateGroup();
    else await this.createGroup();
    this.loading = false;
  }
  async createGroup() {
    try {
      const response = await cornieClient().post("/api/v1/group", this.payload);
      if (response.success) {
        window.notify({ msg: "Group created", status: "success" });
        this.$router.push("/dashboard/provider/settings/group");
      }
    } catch (error: any) {
      console.log(error.response.data);
      window.notify({ msg: "Group not created", status: "error" });
      //this.$router.push('/dashboard/provider/settings/group')
    }
  }

  async updateGroup() {
    const url = `/api/v1/group/${this.id}`;
    const payload = { ...this.payload };
    try {
      const response = await cornieClient().put(url, payload);
      if (response.success) {
        window.notify({ msg: "Group updated", status: "success" });
        this.$router.push("/dashboard/provider/settings/group");
      }
    } catch (error) {
      window.notify({ msg: "Group not updated", status: "error" });
    }
  }
  async created() {
    this.setGroup();
    const data = await this.getDropdowns("group");
    this.dropdowns = data;
  }
}
</script>
<style>
.outline-primary {
  border: 2px solid #080056;
}
</style>
