<template>
  <div class="bg-white rounded p-5 mt-5">
    <span
      class="flex border-b-2 w-full font-semibold text-xl text-primary py-2 mx-auto"
    >
      {{ allaction }} Group
    </span>
    <div class="w-full h-screen overflow-y-auto">
      <form class="mt-5 w-full pr-3" @submit.prevent="submit">
        <div>
          <div class="border-b-2 border-dashed border-gray-100">
            <accordion-component title="Basic info" :opened="true">
              <template v-slot:misc>
                <info></info>
              </template>
              <template v-slot:default>
                <div class="w-full grid grid-cols-2 gap-4 mt-5">
                  <cornie-input label="Group ID" placeholder="--Autogenerated--" disabled />
                  <fhir-input
                    reference="http://hl7.org/fhir/ValueSet/group-type"
                    class="w-full"
                    :rules="required"
                    v-model="type"
                    label="Type"
                    placeholder="--Select--"
                  />
                  <cornie-select
                    :rules="required"
                    :items="['descriptive', 'actual']"
                    v-model="state"
                    label="State"
                    placeholder="--Select--"
                  >
                  </cornie-select>
                  <cornie-input
                    label="Name"
                    placeholder="--Enter--"
                    v-model="name"
                  />
                  <cornie-input
                    label="Code (optional)"
                    placeholder="--Enter--"
                    v-model="code"
                  />
                  <cornie-select
                    :rules="required"
                    :items="[
                      'practitioner',
                      'organization'
                    ]"
                    v-model="managingEntityType"
                    label="Managing Entity Type"
                    placeholder="--Select--"
                  ></cornie-select>
                  <cornie-select
                  v-if="managingEntityType == 'practitioner'"
                    :rules="required"
                    :items="types"
                    v-model="managingEntity"
                    label="Managing Entity"
                    placeholder="--Select--"
                  ></cornie-select>
                </div>
              </template>
            </accordion-component>
          </div>
          <div class="border-b-2 border-dashed border-gray-100" v-if="state == 'actual'">
              <accordion-component title="Members" :opened="true">
                <template v-slot:misc>
                  <info></info>
                </template>
                <template v-slot:default>
                  <div>
                      <button
                        class="mt-5 font-bold text-sm text-red-500 flex items-center"
                        type="button"
                        @click="showMember = true"
                      >
                        <div class="mr-2 uppercase">add Member(s)</div>
                        <plus-icon class="fill-current text-primary" />
                      </button>
                  </div>
                  <div class="grid grid-cols-12 mt-5">
                    <div
                      class="flex justify-between col-span-3 pr-5"
                      :class="[
                        index !== actorsList.length - 1
                          ? 'border-r border-gray-400'
                          : '',
                        index % 2 !== 0 ? 'pl-5' : '',
                        index === actorsList.length - 1 ? '' : '',
                      ]"
                      v-for="(actor, index) in actorsList"
                      :key="actor.id"
                    >
                      <div class="flex justify-center items-center">
                        <div class="h-12 w-12 rounded-full overflow-hidden mr-1">
                          <img
                            :src="actor?.image || actor?.practitioner?.image"
                            class="h-full w-full"
                            v-if="actor?.image || actor?.practitioner?.image"
                          />
                          <div
                            class="h-full w-full rounded-full overflow-hidden flex items-center justify-center bg-blue-500 text-white-cotton-ball font-bold"
                            v-else
                          >
                            {{ actor?.name?.substr(0, 2).toUpperCase() || (actor?.practitioner?.firstName +''+ actor?.practitioner?.lastName).substr(0, 2).toUpperCase()}}
                          </div>
                        </div>
                        <div class="flex flex-col items-start">
                          <div class="mb-0 font-bold text-sm">
                            <div class="flex justify-center items-center">
                              <div class="mr-1">
                                {{ actor?.name || actor?.practitioner?.firstName +' '+ actor?.practitioner?.lastName}}
                              </div>
                              <div
                                class="font-bolder text-gray-400 mr-1"
                                v-if="actor.job"
                              >
                                •
                              </div>
                              <div class="text-xs text-gray-400">
                                {{ actor?.job  || actor?.practitioner?.jobDesignation}}
                              </div>
                            </div>
                          </div>
                          <div class="text-xs text-gray-400">{{ actor?.type || 'Practitioner' }} | {{ actor?.role}}</div>
                        </div>
                      </div>
                      <div class="flex justify-center items-center">
                        <button
                          v-if="id"
                          class="border-0"
                          type="button"
                          @click="deleteItemId(actor.id)"
                        >
                          <delete-icon />
                        </button>
                        <button
                        v-else
                          class="border-0"
                          type="button"
                          @click="deleteMember(actor.id)"
                        >
                          <delete-icon />
                        </button>
                      </div>
                    </div>
                  </div>
                  <div class="mt-5 cursor-pointer" @click="showViewMember = true">
                    <span class="uppercase font-bold text-sm text-danger">{{ actorsList.length }} Added</span>
                  </div>
                  
                </template>
              </accordion-component>
           </div>
        </div>
        <span class="flex justify-end w-full pb-96">
          <button
            @click="$router.push('/dashboard/provider/settings/group')"
            type="button"
            class="border border-primary rounded-md text-black mt-5 mr-3 py-2 px-8 focus:outline-none hover:bg-primary hover:text-white"
          >
            Cancel
          </button>

          <cornie-btn
            :loading="loading"
            type="submit"
            class="bg-danger rounded-md text-white mt-5 px-3 focus:outline-none hover:opacity-90"
          >
            Save
          </cornie-btn>
        </span>
      </form>
    </div>
  </div>
   <add-actor
      v-model="showMember"
      @update-actors-list="updateActorsList"
      :memberToDelete="memberToDelete"
      @memberDeleted="memberToDelete = ''"
      :groupId="id"
    />
    <viewmember-modal v-model="showViewMember" :groupId="id" :groupMembers="actorsList"/>
</template>
<script lang="ts">
import { Options, Vue } from "vue-class-component";
//import IGroup , { GroupMembers } from "@/types/IGroup";
import IGroup from "@/types/IGroup";
import { cornieClient } from "@/plugins/http";
import { namespace } from "vuex-class";
import { string } from "yup";
import { Prop, Watch } from "vue-property-decorator";

import IPractitioner, {
    PractitionerLocationRole,
  } from "@/types/IPractitioner";
import IDevice from "@/types/IDevice";
import { IPatient } from "@/types/IPatient";
import Period from "@/types/IPeriod";
import IRequest, {Medications} from "@/types/IRequest";

import AccordionComponent from "@/components/form-accordion.vue";
import CornieInput from "@/components/cornieinput.vue";
import CornieSelect from "@/components/cornieselect.vue";
import CornieSelectQuestion from "@/components/cornieselect-question.vue";
import Textarea from "@/components/textarea.vue";
import PhoneInput from "@/components/phone-input.vue";
import OrgSelect from "@/components/orgSelect.vue";
import ColumnFilter from "@/components/columnfilter.vue";
import DEdit from "@/components/icons/dedit.vue";
import CDelete from "@/components/icons/cdelete.vue";
import CAdd from "@/components/icons/cadd.vue";
import AddIcon from "@/components/icons/add.vue";
import DatePicker from "@/components/daterangepicker.vue";
import SingleDatePicker from "./datepicker.vue";

import Info from "@/components/icons/info-blue-bg.vue";
import Avatar from "@/components/avatar.vue";
import EditIcon from "@/components/icons/edit-purple.vue";
import DeleteIcon from "@/components/icons/delete-red.vue";
import PlusIcon from "@/components/icons/plus.vue";
import FhirInput from "@/components/fhir-input.vue";
import AddActor from "./components/AddActor.vue";
import ViewmemberModal from "./components/Members.vue";
import { IOrganization } from "@/types/IOrganization";

const group = namespace("group");
const dropdown = namespace("dropdown");
const practitioner = namespace("practitioner");
const device = namespace("device");
const roles = namespace("roles")
const patients = namespace("patients");
const request = namespace("request");
const account = namespace("user");
const organization = namespace("organization");

@Options({
  components: {
    CornieInput,
    CornieSelect,
    CornieSelectQuestion,
    OrgSelect,
    ColumnFilter,
    SingleDatePicker,
    PlusIcon,
    Textarea,
    DEdit,
    CDelete,
    CAdd,
    AddIcon,
    PhoneInput,
    DatePicker,
    AccordionComponent,
    Info,
    FhirInput,
    Avatar,
    EditIcon,
    DeleteIcon,
    AddActor,
    ViewmemberModal,
  },
})
export default class AddGroup extends Vue {
  @Prop({ type: String, default: "" })
  id!: string;

  @group.Action
  getGroupById!: (id: string) => IGroup;


   @practitioner.State
  practitioners!: IPractitioner[];

  @device.State
  devices!: IDevice[];

  @practitioner.Action
  fetchPractitioners!: () => Promise<boolean>;

  @device.Action
  fetchDevices!: () => Promise<boolean>;

  @account.Getter
  authPractitioner!: IPractitioner;

  @roles.State
  roles!: { id: string; name: string }[];

  @roles.Action
  getRoles!: () => Promise<void>;

  @patients.State
  patients!: IPatient[];

  @patients.Action
  fetchPatients!: () => Promise<void>;

  @request.State
  requests!: any[];

  @request.Action
  fetchRequests!: (page?:number, limit?:number) => Promise<void>;

  @organization.State
  organizationInfo!: IOrganization;

  @organization.Action
  fetchOrgInfo!: () => Promise<void>;

  @group.Action
  deleteGroupMembers!: (id: string) => Promise<boolean>;

  loading = false;
  expand = false;
  isVisible = "";
  opened = true;
  openedR = false;
  openedT = false;
  state = "actual";
  status = 'active';
  type = "";
  name = "";
  code = null;
  quantity = "";
  managingEntity = "";
  characteristicsCode = "";
  valueCodeableConcept = "";
  valueBoolean = "";
  valueQuantity = "";
  valueRange = "";
  valueRef = "";
  exclude = "";
  period = {} as Period;
  memberPeriod = "";
  memberStatus = "";
  memberEntity = "--Select--";
  launchMemberdiag = false;
  aoption = "Active";
  managingEntityType = "practitioner";
  managingOrganizationId = undefined;
  managingPractitionerId = undefined;

  organizations = [] as any;

  showMember = false;
  showViewMember = false;

  avatarSrc = "";
  show = false;
  options = [
    { text: "Active", value: true },
    { text: "Inactive", value: false },
  ];
  items = ["Active", "Inactive"];
  required = string().required();
  dropdowns = {} as IIndexableObject;

  @dropdown.Action
  getDropdowns!: (a: string) => Promise<IIndexableObject>;


  @Watch("id")
  idChanged() {
    this.setGroup();
  }
  async setGroup() {
    const group = await this.getGroupById(this.id);
    if (!group) return;

    this.state = group.state;
    (this.status as any) = group.status;
    this.type = group.type;
    this.name = group.name;
    (this.code as any) = group.code;
    this.quantity = group.quantity;
    this.managingEntity = group.managingEntityName;
    this.actorsList = group.members;
    this.managingEntityType = group.managingEntityType;
    this.managingPractitionerId = group.managingPractitionerId;
    this.managingOrganizationId = group.managingOrganizationId;

  }
  get payload() {
    return {
        state: this.state,
        status: this.status,
        type: this.type,
        name: this.name,
        // code: this.code,
        // quantity: this.quantity,
        //managingEntity: this.managingEntity,
        managingEntityType: this.managingEntityType,
        managingOrganizationId: this.managingOrganizationId || this.authPractitioner.organizationId,
        managingPractitionerId: this.managingPractitionerId || undefined,
        members: this.actorsList.map((item: any) => {
        return {
          practitionerId: item.id,
          period: item.period,
          role: item.role,
        };
      }),
    };
  }
   get updatePayload() {
    return {
        state: this.state,
        status: this.status,
        type: this.type,
        name: this.name,
        // code: this.code,
        // quantity: this.quantity,
        //managingEntity: this.managingEntity,
        managingEntityType: this.managingEntityType,
        managingOrganizationId: this.getOrgainizationId(this.managingOrganizationId),
        managingPractitionerId: this.getPractionerId(this.managingPractitionerId),
        members: this.actorsList.map((item: any) => {
        return {
          practitionerId: item.id,
          period: item.period,
          role: item.role,
        };
      }),
    };
  }
  getPractionerId(name: any) {
    const pt = this.practitioners.find((i: any) => i.firstName && i.lastName === name);
    return pt ? `${pt.id} ` : "";
  }
   getOrgainizationId(name: any) {
    const pt = this.organizations.find((i: any) => i.name === name);
    return pt ? `${pt.id} ` : "";
  }
  get allaction() {
    return this.id ? "Edit" : "Add a";
  }

  actorsList = [] as any;
  memberToDelete = "" as string;

  get types(){
    switch (this.managingEntityType) {
      case "practitioner":
        this.managingPractitionerId = this.managingEntity as any;
        return this.allpractitioners;
      case "organization":
        this.managingOrganizationId = this.managingEntity as any
        return this.allOrganizations;
      default:
        break;
    }
  }

  async updateActorsList(actors: any) {
    this.actorsList = [actors[0], ...this.actorsList];

    this.memberEntity = "--Select--";
  }

  async deleteItemId(id: string) {
    const confirmed = await window.confirmAction({
      message:
        "Are you sure you want to delete this group? This action cannot be undone.",
      title: "Delete Group",
    });
    if (!confirmed) return;

    if (await this.deleteGroupMembers(id))
      window.notify({ msg: "Group deleted", status: "error" });
    else window.notify({ msg: "Group not deleted", status: "error" });
  }


  async deleteMember(id: string) {
    const confirm = await window.confirmAction({
      message: "Are you sure you want to remove member?",
      title: "Remove member",
    });

    if (!confirm) return;

    this.actorsList = [
      ...this.actorsList.filter((item: any) => item.id !== id),
    ];

    this.memberToDelete = id;
  }

  get allpractitioners() {
      return this.practitioners.map((role) => ({ code: role.id, display: role.firstName +' '+ role.lastName }));
  }
  get allOrganizations() { 
    return this.organizations.map((organization:any) => ({ code: organization.id, display: organization.name  }));
  }




  async submit() {
    this.loading = true;
    if (this.id) await this.updateGroup();
    else await this.createGroup();
    this.loading = false;
  }
  async createGroup() {
    try {
      const response = await cornieClient().post("/api/v1/group", this.payload);
      if (response.success) {
        window.notify({ msg: "Group created", status: "success" });
        this.$router.push("/dashboard/provider/settings/group");
      }
    } catch (error: any) {
      console.log(error.response.data);
      window.notify({ msg: "Group not created", status: "error" });
      //this.$router.push('/dashboard/provider/settings/group')
    }
  }

  async updateGroup() {
    const url = `/api/v1/group/${this.id}`;
    const payload = { ...this.updatePayload };
    try {
      const response = await cornieClient().put(url, payload);
      if (response.success) {
        window.notify({ msg: "Group updated", status: "success" });
        this.$router.push("/dashboard/provider/settings/group");
      }
    } catch (error) {
      window.notify({ msg: "Group not updated", status: "error" });
    }
  }

   async fetchAllOrganizations() {
        try {
          const { data } = await cornieClient().get(
            `/api/v1/organization/`
          );
          this.organizations = data;
        } catch (error) {
          window.notify({
            msg: "There was an error when fetching organization",
            status: "error",
          });
        }
  }
  async created() {
    await this.fetchPractitioners();
    this.setGroup();

    const data = await this.getDropdowns("group");
    this.dropdowns = data;
    await this.fetchAllOrganizations();

    await this.fetchDevices();
    await this.getRoles();
    await this.fetchRequests();
    await this.fetchPatients();
  }
}
</script>
<style>
.outline-primary {
  border: 2px solid #080056;
}
</style>
