<template>
  <div>
    <cornie-card-title class="pb-6 flex items-center justify-between">
      <div class="flex items-center space-x-4">
        <icon-btn @click="$emit('close')">
          <arrow-left stroke="#ffffff" />
        </icon-btn>
        <p class="text-3xl font-bold">Collect payment</p>
      </div>
      <div class="text-red-500 text-base cursor-pointer">View Bill</div>
    </cornie-card-title>

    <cornie-card-text class="flex-grow scrollable">
      <v-form class="flex-grow flex flex-col">
        <cornie-input
          class="w-full"
          placeholder="Autogenerated"
          label="Name"
          v-model="request.patient.name"
          :disabled="true"
        />
        <cornie-input
          class="w-full"
          placeholder="Autogenerated"
          label="Account"
          v-model="account"
          :disabled="true"
        />
        <cornie-input
          class="w-full"
          placeholder="Autogenerated"
          label="Total Bill (N)"
          v-model="totalBill"
          :disabled="true"
        />
        <cornie-input
          class="w-full"
          placeholder="Autogenerated"
          label="Co-payment Amount (N)"
          v-model="coPaymentAmt"
          :disabled="true"
        />
        <cornie-input
          class="w-full"
          placeholder="Autogenerated"
          label="Amount to Receive (N)"
          v-model="amtToReceive"
          :disabled="true"
        />
        <cornie-select
          class="w-full"
          label="payment Type"
          placeholder="Select one"
          v-model="paymentType"
          :items="['Cash', 'Cash', 'Insurance', 'Wallet', 'Others']"
        />
        <div v-if="paymentType === 'Others'">
          <cornie-input
            class="w-full"
            placeholder="Autogenerated"
            label="Specify the payment type used"
            v-model="otherPaymentType"
            :disabled="true"
          />
        </div>
        <div class="-mt-4">
          <text-area
            placeholder="Type your note"
            label="Notes"
            v-model="note"
            class="w-full"
            rows="0"
          />
        </div>

        <div class="mt-12">
          <cornie-checkbox
            v-model="CompleteDispense"
            :disabled="true"
            :label="'Complete Dispense'"
          />
        </div>
      </v-form>
    </cornie-card-text>

    <div class="flex items-center justify-end mt-24">
      <div class="flex items-center mb-6">
        <cornie-btn
          @click="$emit('close')"
          class="border-primary border-2 px-6 py-1 mr-3 rounded-lg text-primary"
        >
          Cancel
        </cornie-btn>
        <cornie-btn
          :loading="loading"
          type="submit"
          class="text-white bg-danger px-3 py-1 rounded-lg"
        >
          Submit
        </cornie-btn>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import { Options, Vue } from "vue-class-component";
import CornieDialog from "@/components/CornieDialog.vue";
import CornieCard from "@/components/cornie-card";
import ArrowLeft from "@/components/icons/arrowleft.vue";
import IconInput from "@/components/IconInput.vue";
import SearchIcon from "@/components/icons/search.vue";
import CancelIcon from "@/components/icons/cancel.vue";
import IconBtn from "@/components/CornieIconBtn.vue";
import CornieInput from "@/components/cornieinput.vue";
import CornieSelect from "@/components/cornieselect.vue";
import CustomCheckbox from "@/components/custom-checkbox.vue";
import TextArea from "@/components/textarea.vue";
import { Prop, PropSync, Watch } from "vue-property-decorator";
import CornieBtn from "@/components/CornieBtn.vue";
import { namespace } from "vuex-class";
import { CornieUser } from "@/types/user";
import { string } from "yup";
import { cornieClient } from "@/plugins/http";
import CornieCheckBox from "@/components/corniecheckbox.vue";
import IDispenseInfo from "@/types/IDispenseInfo";

import { debounce } from "lodash";

const orgFunctions = namespace("OrgFunctions");
const user = namespace("user");

@Options({
  name: "ModifyRequest",
  components: {
    CornieDialog,
    ...CornieCard,
    ArrowLeft,
    IconBtn,
    CornieInput,
    CornieSelect,
    CustomCheckbox,
    CornieBtn,
    CornieCheckBox,
    CancelIcon,
    IconInput,
    SearchIcon,
  },
})
export default class PostBillModal extends Vue {

  
  @Prop({ type: Object, default: "" })
  request!: IDispenseInfo;

  loading = false;

  name = "";
  account = "";
  totalBill = "";
  coPaymentAmt = "";
  amtToReceive = "";
  paymentType = "";
  note = "";
  CompleteDispense = true;
  otherPaymentType = "";

  @user.Getter
  authCurrentLocation!: any;

  get locationId() {
    // return this.authCurrentLocation;
    return "21b84341-2051-4cad-b6b6-feae04f81215";
  }

  postBill() {}

  sharePayLink() {}
}
</script>

<style scoped></style>
