<template>
  <cornie-dialog v-model="show" right class="w-2/3 h-full">
    <cornie-card
      height="100%"
      class="flex flex-col h-full bg-white px-6 overflow-y-scroll"
    >
      <cornie-card-title class="">
        <icon-btn @click="show = false">
          <arrow-left stroke="#ffffff" />
        </icon-btn>
        <div class="w-full">
          <h2 class="font-bold float-left text-lg text-primary ml-3 -mt-1">
            New Sales
          </h2>
          <cancel-icon
            class="float-right cursor-pointer"
            @click="show = false"
          />
        </div>
      </cornie-card-title>
      <div class="border px-4 py-6">
        <cornie-card-text class="flex-grow scrollable">
          <v-form class="flex-grow flex flex-col" @submit="submit">
            <div class="grid grid-cols-2 gap-6">
              <cornie-input
                class="w-full"
                label="Reference"
                placeholder="Autogenerated"
                v-model="refernce"
                :disabled="true"
              />
              <date-picker
                class="w-full"
                label="Sales Date"
                v-model="salesDate"
                :disabled="salesData"
              />

              <div class="relative">
                <span
                  class="z-20 text-red-500 float-right font-bold text-sm absolute right-0 cursor-pointer"
                  @click.stop="addCustomerModal = true"
                  >Add</span
                >
                <auto-complete
                  v-bind="$attrs"
                  label="Customer"
                  placeholder="Select one"
                  v-model="customerId"
                  :rules="required"
                  :items="customers"
                  @query="fetchCustomers"
                  :disabled="salesData"
                >
                  <template #item="{ item }">
                    <div class="w-full flex items-center my-1">
                      <!-- <avatar :src="item.image" /> -->
                      <div class="ml-4 flex flex-col">
                        <span class="text-xs">{{ item.name }}</span>
                        <span class="text-xs font-semibold text-gray-500">
                          {{ item.mrn }}
                        </span>
                      </div>
                    </div>
                  </template>
                </auto-complete>
              </div>

              <cornie-select
                class="w-full"
                label="Type"
                placeholder="--Select--"
                v-model="type"
                :items="['pickup', 'delivery']"
                :disabled="salesData"
              />
            </div>

            <div
              v-if="!salesData || !checkSales"
              class="flex items-center justify-between mt-12"
            >
              <div class="">
                <span
                  class="mb-2 w-full rounded-full"
                  @click="showDatalist = !showDatalist"
                >
                  <icon-input
                    autocomplete="off"
                    class="border border-gray-600 rounded-full focus:outline-none"
                    type="search"
                    placeholder="Search"
                    v-model="medQuery"
                  >
                    <template v-slot:prepend>
                      <search-icon />
                    </template>
                  </icon-input>
                </span>
                <div
                  :class="[
                    !showDatalist ? 'hidden' : 'o',
                    medicationData.length === 0 ? 'h-20' : 'h-auto',
                  ]"
                  class="absolute shadow bg-white border-gray-400 border top-100 z-40 left-0 m-3 rounded overflow-auto mt-2 svelte-5uyqqj"
                  style="width: 50%"
                >
                  <div class="flex flex-col w-full p-3">
                    <div
                      v-for="(item, i) in medicationData"
                      :key="i"
                      class="cursor-pointer mb-3 w-full border-gray-100 rounded-xl hover:bg-white-cotton-ball"
                    >
                      <div class="flex items-center justify-between">
                        <div
                          class="w-full text-sm items-center p-2 border-transparent border-l-2 relative"
                        >
                          {{ item.name }}
                          <p class="text-xs text-gray-400 italic">
                            {{ item?.brandCode }}
                          </p>
                        </div>

                        <cornie-radio
                          name="search"
                          @click="selectMed(item, item.name)"
                        />
                      </div>
                    </div>
                  </div>
                  <div v-if="medicationData.length === 0">
                    <span
                      class="py-2 px-5 text-sm text-gray-600 text-center flex justify-center"
                      >No Match!</span
                    >
                  </div>
                </div>

                <!-- <cornie-card-text
                  class="flex justify-end"
                  v-if="medicationData.length > 0"
                >
                  <cornie-btn
                    @click="showDatalist = false"
                    class="border-primary border-2 px-6 mr-3 rounded-xl text-primary"
                  >
                    Cancel
                  </cornie-btn>
                  <cornie-btn
                    :loading="loading"
                    @click="showDatalist = false"
                    class="text-white bg-danger font-semibold px-6 rounded-xl"
                  >
                    Add
                  </cornie-btn>
                </cornie-card-text> -->
              </div>

              <cornie-btn
                type="submit"
                class="text-white bg-danger px-12 rounded-lg"
                @click.prevent="addMedication"
              >
                <plus-icon-white class="mr-3" />
                Add
              </cornie-btn>
            </div>
          </v-form>

          <cornie-table
            :columns="rawHeaders"
            v-model="items"
            :listmenu="true"
            :check="false"
            class="mt-7"
          >
            <template #actions="{ item }">
              <div
                class="flex items-center hover:bg-gray-100 p-3 cursor-pointer"
                @click="showItem(item.id)"
              >
                <edit-icon class="text-danger fill-current" />
                <span class="ml-3 text-xs">Update</span>
              </div>
              <div
                class="flex items-center hover:bg-gray-100 p-3 cursor-pointer"
                @click="deleteItem(item.id)"
              >
                <delete-icon class="text-danger fill-current" />
                <span class="ml-3 text-xs">Delete</span>
              </div>
            </template>
            <template #quantity="{ item }">
              <div>
                <cornie-input
                  type="number"
                  class="w-full"
                  placeholder="Enter"
                  v-model="quantity"
                />
              </div>
            </template>
            <!-- <template #lineTotal="{ item }">
              <div class="flex space-x-3">
                <span>
                  {{ item.quantity * item.unitPrice  || '0' }}
                </span>
              </div>
            </template> -->
          </cornie-table>

          <div class="mt-8 flex items-start justify-between">
            <div class="w-1/3">
              <div
                class="px-4 py-3 text-sm border rounded-md flex items-center justify-between w-full"
              >
                <span class="w-3/5 text-xs">Coupon | Promo Code</span>
                <input
                  class="w-2/5 self-end"
                  type="text"
                  v-model="coupon"
                  placeholder="----"
                  :disabled="salesData"
                />
              </div>
              <span class="text-xs text-red-500 mt-2 text-right"
                >A Coupon/Promo discount of 20% applies.</span
              >
            </div>

            <div class="w-1/3">
              <table class="w-full">
                <tbody>
                  <tr>
                    <td>Total Discount</td>
                    <td>----</td>
                  </tr>
                  <tr>
                    <td>Sub Total</td>
                    <td>----</td>
                  </tr>
                  <tr>
                    <td class="font-bold">Shipping Cost</td>
                    <td>----</td>
                  </tr>
                  <tr class="">
                    <td class="font-bold">Grand Total</td>
                    <td>----</td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>

          <div class="mt-7">
            <div class="w-full border-gray-300 border-b flex items-center mb-6">
              <span
                class="cursor-pointer px-4 py-1 text-gray-400"
                :class="{
                  'border-red-500 border-b-4 text-black':
                    activeTab === 'Full Payment',
                }"
                @click="activeTab = 'Full Payment'"
              >
                Full Payment
              </span>
              <span
                class="cursor-pointer px-4 py-1 text-gray-400"
                :class="{
                  'border-red-500 border-b-4 text-black':
                    activeTab === 'Split Payment',
                }"
                @click="activeTab = 'Split Payment'"
              >
                Split Payment
              </span>
            </div>

            <div>
              <full-payment
                v-if="activeTab === 'Full Payment'"
                :payments="payments"
                :salesData="salesData"
              />
              <split-payment
                v-if="activeTab === 'Split Payment'"
                :payments="payments"
                :salesData="salesData"
              />
            </div>
          </div>
        </cornie-card-text>
      </div>

      <div
        class="flex items-center justify-between mt-14"
        v-if="checkSales && sales.status !== 'completed'"
      >
        <div>
          <span
            class="text-red-500 font-bold text-base cursor-pointer"
            @click="addSales(0)"
            >Keep On Hold</span
          >
        </div>
        <div class="flex items-center mb-6">
          <cornie-btn
            @click="show = false"
            class="border-primary border-2 px-6 py-1 mr-3 rounded-lg text-primary"
          >
            Cancel
          </cornie-btn>
          <cornie-btn
            :loading="loading"
            type="submit"
            class="text-white bg-danger px-3 py-1 rounded-lg"
            @click="addSales(1)"
          >
            Completed Sales
          </cornie-btn>
        </div>
      </div>
    </cornie-card>
  </cornie-dialog>

  <add-customer v-model="addCustomerModal" />
</template>
<script lang="ts">
import { Options, Vue } from "vue-class-component";
import CornieDialog from "@/components/CornieDialog.vue";
import CornieCard from "@/components/cornie-card";
import IconInput from "@/components/IconInput.vue";
import SearchIcon from "@/components/icons/search.vue";
import ArrowLeft from "@/components/icons/arrowleft.vue";
import CancelIcon from "@/components/icons/cancel.vue";
import PlusIconWhite from "@/components/icons/plus-icon-white.vue";
import IconBtn from "@/components/CornieIconBtn.vue";
import CornieInput from "@/components/cornieinput.vue";
import CornieSelect from "@/components/cornieselect.vue";
import CustomCheckbox from "@/components/custom-checkbox.vue";
import { Prop, PropSync, Watch } from "vue-property-decorator";
import CornieBtn from "@/components/CornieBtn.vue";
import { namespace } from "vuex-class";
import { CornieUser } from "@/types/user";
import { string } from "yup";
import AutoComplete from "@/components/autocomplete.vue";
import { cornieClient } from "@/plugins/http";
import CornieRadio from "@/components/cornieradio.vue";
import IAppointmentRoom from "@/types/IAppointmentRoom";

import DatePicker from "@/components/datepicker.vue";
import SearchInput from "@/components/singleSearch.vue";
import { first, getTableKeyValue } from "@/plugins/utils";

import TableOptions from "@/components/table-options.vue";
import CornieTable from "@/components/cornie-table/CornieTable.vue";
import FullPayment from "./components/FullPayment.vue";
import SplitPayment from "./components/SplitPayment.vue";
import AddCustomer from "./AddCustomer.vue";
import CornieSearch from "@/components/search-input.vue";

import { debounce } from "lodash";

import search from "@/plugins/search";

const hierarchy = namespace("hierarchy");
const orgFunctions = namespace("OrgFunctions");
const user = namespace("user");
const appointmentRoom = namespace("appointmentRoom");

@Options({
  name: "POSDialog",
  components: {
    CornieDialog,
    ...CornieCard,
    ArrowLeft,
    IconBtn,
    CornieInput,
    CornieSelect,
    CustomCheckbox,
    CornieBtn,
    AutoComplete,
    CornieRadio,
    DatePicker,
    SearchInput,
    CornieTable,
    TableOptions,
    FullPayment,
    SplitPayment,
    CancelIcon,
    CornieSearch,
    PlusIconWhite,
    AddCustomer,
    IconInput,
    SearchIcon,
  },
})
export default class PosDialog extends Vue {
  @PropSync("modelValue", { type: Boolean, default: false })
  show!: boolean;

  @Prop({ type: String, default: "" })
  id!: string;

  @Prop({ type: Object, default: <any>{} })
  sales!: any;

  @Prop({ type: Boolean, default: false })
  salesData!: boolean;

  required = string().required();

  activeMedIndex = 0;

  showDatalist = false;
  quantity = 1;

  query = "";
  medQuery = "";
  addCustomerModal = false;
  selectedMed = {};

  loading = false;
  activeTab = "Full Payment";
  customerDetails = <any>[];
  medicationDetails = <any>[];

  status = this.sales?.status || "";
  type = this.sales?.type || "";
  coupon = this.sales?.coupon || "";
  customerId = "";
  customer = {
    name: this.sales?.customer?.name || "",
  };
  reference = this.sales?.reference || "";
  salesDate = this.sales?.createdAt || "";
  medications = this.sales?.medications || <any>[];
  medication = "";
  payments = this.sales?.payments || [
    {
      amount: "",
      paymentType: "",
      total: 0,
    },
  ];

  @user.Getter
  authCurrentLocation!: any;

  getKeyValue = getTableKeyValue;
  preferredHeaders = [];
  rawHeaders = [
    {
      title: "ITEM NAME",
      key: "itemName",
      show: true,
    },
    {
      title: "UNIT PRICE",
      key: "unitPrice",
      show: true,
    },
    {
      title: "QUANTITY",
      key: "quantity",
      show: true,
    },
    {
      title: "LINE TOTAL",
      key: "lineTotal",
      show: true,
    },
  ];

  get checkSales() {
    if (Object.entries(this.sales).length === 0) {
      return true;
    }
    return false;
  }

  // get locationId() {
  //   return this.authCurrentLocation;
  // }

  get locationId() {
    return "21b84341-2051-4cad-b6b6-feae04f81215";
  }

  @Watch("quantity")
  updateLineTotal() {
    this.medications?.map((medication: any, i: number) => {
      return {
        ...medication,
        lineTotal: ((medication.unitPrice as number) *
          medication.quantity) as number,
      };
    });
  }

  get items() {
    const dMed = this.medications?.map((medication: any, i: number) => {
      return {
        ...medication,
        action: medication.id,
        itemName: medication.name,
        unitPrice: medication.unitPrice,
        quantity: this.quantity,
        lineTotal: ((medication.unitPrice as number) *
          medication.quantity) as number,
      };
    });
    if (!this.query) return dMed;
    return search.searchObjectArray(dMed, this.query);
  }

  selectMed(item: any) {
    this.$emit("selected", item);
    console.log("item", item);
    this.selectedMed = item;
    this.showDatalist = false;
  }

  fetchCustomers(query: string) {
    debounce(async () => {
      try {
        const { data } = await cornieClient().get(
          `/api/v1/pharmacy/find-customer/?query=${query}`
        );
        this.customerDetails = data || [];
      } catch (error) {
        window.notify({
          msg: "There was an error fetching customers details",
          status: "error",
        });
      }
    }, 1000)();
  }

  get customers() {
    const xCustomers = this.customerDetails?.map((customer: any) => {
      return {
        ...customer,
        code: customer.id,
        display: customer.name,
        name: customer.name,
        mrn: customer.mrn,
        id: customer.id,
      };
    });
    if (!this.query) return xCustomers;
    return search.searchObjectArray(xCustomers, this.query);
  }

  async fetchMedications(query: string) {
    try {
      const { data } = await cornieClient().get(
        `/api/v1/pharmacy/find-medication/${this.locationId}/?query=${query}`
      );
      this.medicationDetails = data || [];
    } catch (error) {
      window.notify({
        msg: "There was an error fetching medications",
        status: "error",
      });
    }
  }

  get medicationData() {
    const xMedications = this.medicationDetails?.map((medication: any) => {
      return {
        ...medication,
        code: medication.id,
        name: medication.name,
        display: medication.brandCode,
        brandCode: medication.brandCode,
        unitPrice: medication.unitPrice,
        lineTotal: ((medication.unitPrice as number) *
          medication.quantity) as number,
        quantity: 1,
        available: medication.available,
        form: medication.form,
        id: medication.id,
        totalDiscount: medication,
      };
    });
    if (!this.query) return xMedications;
    return search.searchObjectArray(xMedications, this.query);
  }

  get patientName() {
    const pId = this.customerDetails.find((el: any) => {
      el.id === this.customerId;
    });
    return pId.name;
  }

  addMedication() {
    this.medications.push({ ...this.selectedMed });
    this.activeMedIndex = this.medications.length - 1;
  }

  async addSales(type: any) {
    if (type === 0) {
      this.status = "on-hold";
    } else if (type === 1) {
      this.status = "completed";
    }
    const newSales = {
      patientId: this.customerId,
      type: this.type,
      status: this.status,
      coupon: this.coupon,
      medications: this.medications.map((el: any) => {
        return {
          ...el,
          dispensedProductId: el.id,
          reasonForSubstitution: el.reasonForSubstitution,
          quantity: el.quantity,
        };
      }),
      payments: this.payments.map((el: any) => {
        return {
          ...el,
          amount: el.amount,
          paymentType: el.paymentType,
        };
      }),
      customer: {
        name: this.customerId,
      },
    };
    try {
      const { data } = await cornieClient().post(
        `/api/v1/pharmacy/pos-dispense/${this.locationId}`,
        { ...newSales }
      );
    } catch (error) {
      window.notify({
        msg: "An error occured",
        status: "error",
      });
    }
  }

  @Watch("medQuery")
  typed(medQuery: string) {
    this.fetchMedications(medQuery);
  }

  deleteItem(itemId: string) {
    this.medications.filter((el: any) => {
      el.id = itemId;
      this.medications = this.medications.splice(el, 1);
    });
  }

  async created() {}
}
</script>

<style scoped>
td {
  padding: 16px;
}
</style>
