<template>
  <cornie-dialog v-model="show" right class="w-2/3 h-full">
    <cornie-card
      height="100%"
      class="flex flex-col h-full bg-white px-6 overflow-y-scroll"
    >
      <cornie-card-title class="">
        <icon-btn @click="show = false">
          <arrow-left stroke="#ffffff" />
        </icon-btn>
        <div class="w-full">
          <h2 class="font-bold float-left text-lg text-primary ml-3 -mt-1">
            New Sales
          </h2>
          <cancel-red-bg
            class="float-right cursor-pointer"
            @click="show = false"
          />
        </div>
      </cornie-card-title>
      <div class="border px-4 py-6">
        <cornie-card-text class="flex-grow scrollable">
          <v-form class="flex-grow flex flex-col">
            <div class="grid grid-cols-2 gap-6">
              <cornie-input
                class="w-full"
                label="Reference"
                placeholder="Autogenerated"
                v-model="reference"
                :disabled="true"
              />
              <date-picker
                class="w-full"
                label="Sales Date"
                v-model="salesDate"
                :disabled="salesData || checkSales"
              />

              <div class="relative">
                <span
                  v-if="!checkSales"
                  class="z-20 text-red-500 float-right font-bold text-sm absolute right-0 cursor-pointer"
                  @click.stop="addCustomerModal = true"
                  >Add</span
                >
                <auto-complete
                  v-bind="$attrs"
                  label="Customer"
                  placeholder="Select one"
                  v-model="customerId"
                  :rules="required"
                  :items="customers"
                  @query="fetchCustomers"
                  :disabled="salesData && checkSales"
                >
                  <template #item="{ item }">
                    <div class="w-full flex items-center my-1">
                      <!-- <avatar :src="item.image" /> -->
                      <div class="ml-4 flex flex-col">
                        <span class="text-xs">{{ item.name }}</span>
                        <span class="text-xs font-semibold text-gray-500">
                          {{ item.mrn }}
                        </span>
                      </div>
                    </div>
                  </template>
                </auto-complete>
              </div>

              <cornie-select
                class="w-full"
                label="Type"
                placeholder="--Select--"
                v-model="type"
                :items="['pickup', 'delivery']"
                :disabled="salesData && checkSales"
              />
            </div>
          </v-form>

          <div
            class="flex items-center justify-end my-6"
            v-if="!salesData || !checkSales"
          >
            <cornie-btn
              type="submit"
              class="text-white bg-danger px-12 rounded-lg"
              @click="searchMedication = true"
            >
              <plus-icon-white class="mr-3" />
              Add
            </cornie-btn>
          </div>

          <cornie-table
            :columns="rawHeaders"
            v-model="items"
            :listmenu="true"
            :check="false"
            class="mt-7"
          >
            <template #actions="{ item }">
              <div
                class="flex items-center hover:bg-gray-100 p-3 cursor-pointer"
                @click="showItem(item.id)"
              >
                <edit-icon class="text-danger fill-current" />
                <span class="ml-3 text-xs">Update</span>
              </div>
              <div
                class="flex items-center hover:bg-gray-100 p-3 cursor-pointer"
                @click="deleteItem(item.id)"
              >
                <delete-icon class="text-danger fill-current" />
                <span class="ml-3 text-xs">Delete</span>
              </div>
            </template>
            <template #quantity="{ item }">
              <cornie-input
                type="number"
                class="w-full"
                placeholder="Enter"
                v-model="item.quantity"
                :id="item.id"
              />
            </template>
            <template #lineTotal="{ item }">
              <div class="flex space-x-3">
                <span>
                  {{ item.quantity * item.unitPrice || 0 }}
                </span>
              </div>
            </template>
          </cornie-table>

          <div class="mt-8 flex items-start justify-between">
            <div class="w-1/3">
              <div
                class="px-4 py-3 text-sm border rounded-md flex items-center justify-between w-full"
              >
                <span class="w-3/5 text-xs">Coupon | Promo Code</span>
                <input
                  class="w-2/5 self-end"
                  type="text"
                  v-model="coupon"
                  placeholder="----"
                  :disabled="salesData"
                />
              </div>
              <span class="text-xs text-red-500 mt-2 text-right"
                >A Coupon/Promo discount of 20% applies.</span
              >
            </div>

            <div class="w-1/3">
              <table class="w-full">
                <tbody>
                  <tr>
                    <td>Total Discount</td>
                    <td>----</td>
                  </tr>
                  <tr>
                    <td>Sub Total</td>
                    <td>----</td>
                  </tr>
                  <tr>
                    <td class="font-bold">Shipping Cost</td>
                    <td>----</td>
                  </tr>
                  <tr class="">
                    <td class="font-bold">Grand Total</td>
                    <td>----</td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>

          <div class="mt-7" v-if="!salesData || !checkSales">
            <div class="w-full border-gray-300 border-b flex items-center mb-6">
              <span
                class="cursor-pointer px-4 py-1 text-gray-400"
                :class="{
                  'border-red-500 border-b-4 text-black':
                    activeTab === 'Full Payment',
                }"
                @click="activeTab = 'Full Payment'"
              >
                Full Payment
              </span>
              <span
                class="cursor-pointer px-4 py-1 text-gray-400"
                :class="{
                  'border-red-500 border-b-4 text-black':
                    activeTab === 'Split Payment',
                }"
                @click="activeTab = 'Split Payment'"
              >
                Split Payment
              </span>
            </div>

            <div>
              <full-payment
                v-if="activeTab === 'Full Payment'"
                :payments="payments"
                :salesData="salesData"
              />
              <split-payment
                v-if="activeTab === 'Split Payment'"
                :payments="payments"
                :salesData="salesData"
              />
            </div>
          </div>

          <div v-else>
            <div
              class="grid grid-cols-2 gap-6 mb-6"
              v-for="(payment, idx) in sales.payments"
              :key="idx"
            >
              <div class="relative">
                <span
                  v-if="!checkSales"
                  class="z-20 float-right font-bold text-sm absolute right-0"
                  >{{ payment.status }}</span
                >
                <cornie-input
                  class="w-full"
                  label="Amount Due"
                  placeholder="--Enter--"
                  v-model="payment.amount"
                  :rules="required"
                  :disabled="salesData"
                />
              </div>

              <cornie-select
                class="w-full"
                label="Payment Type"
                placeholder="--Search--"
                v-model="payment.paymentType"
                :items="['pos', 'cash']"
                :disabled="salesData"
              />
            </div>
          </div>
        </cornie-card-text>
      </div>

      <div
        class="flex items-center justify-between mt-14"
        v-if="!salesData || sales.status !== 'completed'"
      >
        <div>
          <span
            class="text-red-500 font-bold text-base cursor-pointer"
            @click="addSales(0)"
            >Keep On Hold</span
          >
        </div>
        <div class="flex items-center mb-6">
          <cornie-btn
            @click="show = false"
            class="border-primary border-2 px-6 py-1 mr-3 rounded-lg text-primary"
          >
            Cancel
          </cornie-btn>
          <cornie-btn
            :loading="loading"
            type="submit"
            class="text-white bg-danger px-3 py-1 rounded-lg"
            @click="addSales(1)"
          >
            Completed Sales
          </cornie-btn>
        </div>
      </div>
    </cornie-card>
  </cornie-dialog>

  <add-customer v-model="addCustomerModal" />
  <add-medications v-model="searchMedication" @addMedication="addMedication" />
</template>
<script lang="ts">
import { Options, Vue } from "vue-class-component";
import CornieDialog from "@/components/CornieDialog.vue";
import CornieCard from "@/components/cornie-card";
import ArrowLeft from "@/components/icons/arrowleft.vue";
import CancelRedBg from "@/components/icons/cancel-red-bg.vue";
import PlusIconWhite from "@/components/icons/plus-icon-white.vue";
import IconBtn from "@/components/CornieIconBtn.vue";
import CornieInput from "@/components/cornieinput.vue";
import CornieSelect from "@/components/cornieselect.vue";
import CustomCheckbox from "@/components/custom-checkbox.vue";
import { Prop, PropSync, Watch } from "vue-property-decorator";
import CornieBtn from "@/components/CornieBtn.vue";
import { namespace } from "vuex-class";
import { CornieUser } from "@/types/user";
import { string } from "yup";
import AutoComplete from "@/components/autocomplete.vue";
import { cornieClient } from "@/plugins/http";
import CornieRadio from "@/components/cornieradio.vue";
import IPossale from "@/types/IPossale";
import DeleteIcon from "@/components/icons/delete.vue";
import EditIcon from "@/components/icons/edit.vue";

import DatePicker from "@/components/datepicker.vue";
import SearchInput from "@/components/singleSearch.vue";
import { first, getTableKeyValue } from "@/plugins/utils";

import TableOptions from "@/components/table-options.vue";
import CornieTable from "@/components/cornie-table/CornieTable.vue";
import FullPayment from "./components/FullPayment.vue";
import SplitPayment from "./components/SplitPayment.vue";
import AddCustomer from "./AddCustomer.vue";
import AddMedications from "./AddMedications.vue";
import CornieSearch from "@/components/search-input.vue";

import { debounce } from "lodash";

import search from "@/plugins/search";

const orgFunctions = namespace("OrgFunctions");
const user = namespace("user");

@Options({
  name: "POSDialog",
  components: {
    CornieDialog,
    ...CornieCard,
    ArrowLeft,
    IconBtn,
    CornieInput,
    CornieSelect,
    CustomCheckbox,
    CornieBtn,
    AutoComplete,
    CornieRadio,
    DatePicker,
    SearchInput,
    CornieTable,
    TableOptions,
    FullPayment,
    SplitPayment,
    CancelRedBg,
    CornieSearch,
    PlusIconWhite,
    AddCustomer,
    AddMedications,
    DeleteIcon,
    EditIcon,
  },
})
export default class PosDialog extends Vue {
  @PropSync("modelValue", { type: Boolean, default: false })
  show!: boolean;

  @Prop({ type: String, default: "" })
  id!: string;

  @Prop({ type: Object, default: "" })
  sales!: IPossale;

  @Prop({ type: Boolean, default: false })
  salesData!: boolean;

  required = string().required();

  showDatalist = false;
  quantity = 1;
  searchMedication = false;

  query = "";
  addCustomerModal = false;

  loading = false;
  activeTab = "Full Payment";
  customerDetails = <any>[];

  status = this.sales?.status || "";
  type = this.sales?.type || "";
  coupon = this.sales?.coupon || "";
  customerId = this.sales?.customer || "";
  customer = {
    name: this.sales?.customer || "",
  };
  reference = this.sales?.identifier || "";
  // salesDate = new Date(this.sales?.createdAt).toLocaleDateString("en-US");
  salesDate = "";
  medications = this.sales?.medications || <any>[];
  payments = this.sales?.payments || [
    {
      amount: "",
      paymentType: "",
      total: 0,
      status: "",
    },
  ];

  @user.Getter
  authCurrentLocation!: any;

  getKeyValue = getTableKeyValue;
  preferredHeaders = [];
  rawHeaders = [
    {
      title: "ITEM NAME",
      key: "itemName",
      show: true,
    },
    {
      title: "UNIT PRICE",
      key: "unitPrice",
      show: true,
    },
    {
      title: "QUANTITY",
      key: "quantity",
      show: true,
    },
    {
      title: "LINE TOTAL",
      key: "lineTotal",
      show: true,
    },
  ];

  get checkSales() {
    if (Object.entries(this.sales).length > 0) {
      return true;
    }
    return false;
  }

  // get locationId() {
  //   return this.authCurrentLocation;
  // }

  get locationId() {
    return "21b84341-2051-4cad-b6b6-feae04f81215";
  }

  get items() {
    const dMed = this.medications?.map((medication: any) => {
      return {
        ...medication,
        action: medication.id,
        itemName: medication.name,
        unitPrice: medication.unitPrice,
        quantity: this.quantity,
        lineTotal: Number(medication.unitPrice * this.quantity),
      };
    });
    if (!this.query) return dMed;
    return search.searchObjectArray(dMed, this.query);
  }

  fetchCustomers(query: string) {
    debounce(async () => {
      try {
        const { data } = await cornieClient().get(
          `/api/v1/pharmacy/find-customer/?query=${query}`
        );
        this.customerDetails = data || [];
      } catch (error) {
        window.notify({
          msg: "There was an error fetching customers details",
          status: "error",
        });
      }
    }, 1000)();
  }

  get customers() {
    const xCustomers = this.customerDetails?.map((customer: any) => {
      return {
        ...customer,
        code: customer.id,
        display: customer.name,
        name: customer.name,
        mrn: customer.mrn,
        id: customer.id,
      };
    });
    if (!this.query) return xCustomers;
    return search.searchObjectArray(xCustomers, this.query);
  }

  get patientName() {
    const pId = this.customerDetails.find((el: any) => {
      el.id === this.customerId;
    });
    return pId.name;
  }

  addMedication(chosenMedication: any) {
    this.medications.push({ ...chosenMedication });
  }

  async addSales(type: any) {
    if (type === 0) {
      this.status = "on-hold";
    } else if (type === 1) {
      this.status = "completed";
    }
    const newSales = {
      patientId: this.customerId,
      type: this.type,
      status: this.status,
      coupon: this.coupon,
      medications: this.medications.map((el: any) => {
        return {
          ...el,
          dispensedProductId: el.id,
          reasonForSubstitution: el.reasonForSubstitution,
          quantity: this.quantity,
        };
      }),
      payments: this.payments.map((el: any) => {
        return {
          ...el,
          amount: el.amount,
          paymentType: el.paymentType,
        };
      }),
      customer: {
        name: this.customerId,
      },
    };
    try {
      const { data } = await cornieClient().post(
        `/api/v1/pharmacy/pos-dispense/${this.locationId}`,
        { ...newSales }
      );
      this.$emit("salesAdded");
    } catch (error) {
      window.notify({
        msg: "An error occured",
        status: "error",
      });
    }
  }

  deleteItem(itemId: string) {
    // this.medications.splice(itemId, 1)
  }

  showItem(id: any) {}

  created() {}
}
</script>

<style scoped>
td {
  padding: 16px;
}
</style>
