<template>
  <div class="p-2">
    <div>
      <accordion-component
        v-if="!$route.path.includes('variant')"
        title="New Product"
        :opened="true"
      >
        <template v-slot:default>
          <div>
            <tabs :items="tabLinks" v-model="currentTab">
              <div>
                 <div class="w-full mb-5">
                    <div class="my-4">
                      <cornie-checkbox
                        :label="'This is an inventory item'"
                        v-model="isInventoryItem"
                        :value="'Yes'"
                      />
                    </div>
          
                  </div>
                  <div class="grid grid-cols-3 gap-4">
                      <auto-complete
                        class="w-full"
                        :label="'Generic Name'"
                        :items="allName"
                        @click="resultData(dataCode)"
                        @input="searchData"
                        v-model="dataCode"
                        :placeholder="'Select'"
                      />

                      <cornie-select
                        class="w-full"
                        :label="'Brand/Manufacturer'"
                        :items="allBrand"
                        @click="resultBrand(dataBrand)"
                        v-model="dataBrand"
                        :placeholder="'Select'"
                      />
                      <cornie-select
                        v-model="dataForm"
                        :label="'Form'"
                        :items="allForms"
                        :placeholder="'Select'"
                        class="w-full"
                        @click="resultPack(dataForm)"
                      />
                      <cornie-input
                        :label="'Pack'"
                        v-model="pack"
                        placeholder="--Autoloaded--"
                        class="w-full"
                        :disabled="true"
                      />
                      <cornie-input
                        :label="'Strength'"
                        v-model="strength"
                        placeholder="--Autoloaded--"
                        class="w-full"
                        :disabled="true"
                      />
                      <cornie-input
                        :label="'NAFDAC Registration No.'"
                        v-model="Nafdac"
                        placeholder="--Autoloaded--"
                        class="w-full"
                        :disabled="true"
                      />
                      <cornie-select
                        :label="'Classification.'"
                        placeholder="--Enter--"
                        :items="[
                          'General Health',
                          'Devices',
                          'Sexual Wellness',
                          'Personal Care',
                          'Nutrition, Fitness & Supplements',
                        ]"
                        v-model="classification"
                      />
                      <cornie-select
                        :label="'Sub-classification.'"
                        placeholder="--Enter--"
                        :items="getSubClassify"
                        v-model="subClassification"
                      />
                      <cornie-select
                        v-model="category"
                        :label="'Category'"
                        placeholder="--Select--"
                        :items="[
                          'Over-the-Counter Medicines',
                          'Prescription Only Medicine',
                          'Pharmacy Medicine',
                          'Controlled Drugs',
                        ]"
                      />

                      <div class="">
                        <span
                          class="flex capitalize mb-5 text-black text-sm font-semibold"
                        >
                          Discount applicable?
                        </span>
                        <div class="flex items-end -mb-2">
                          <span class="mr-14"
                            ><cornieradio
                              v-model="applyDiscount"
                              :label="'Yes'"
                              :value="true"
                            />
                          </span>
                          <cornieradio
                            :label="'No'"
                            v-model="applyDiscount"
                            :value="false"
                          />
                        </div>
                      </div>
                        <cornie-input
                          v-model="itemCode"
                          :label="'Item Code'"
                          placeholder="Autogenerated"
                          :disabled="true"
                        />
                  </div>
              </div>

              <div>
                  <div class="w-full mb-5">
                    <div class="my-4">
                      <cornie-checkbox
                        :label="'This is an inventory item'"
                        v-model="isInventoryItem"
                        :value="'Yes'"
                      />
                    </div>
                  </div>
                  <div class="w-full grid gap-4 grid-cols-3">
                    <cornie-input
                      class="w-full"
                      :label="'Generic Name'"
                      v-model="genericName"
                      :placeholder="'--Enter--'"
                    />

                    <cornie-input
                      class="w-full"
                      :label="'Brand/Manufacturer'"
                      v-model="genericCode"
                      :placeholder="'--Enter--'"
                    />
                     <cornie-input
                        v-model="form"
                        :label="'Form'"
                        :placeholder="'--Enter--'"
                        class="w-full"
                      />
                      <cornie-input
                        :label="'Strength'"
                        v-model="strength"
                        placeholder="--Enter--"
                        class="w-full"
                      />
                      <cornie-input
                        :label="'Pack'"
                        v-model="pack"
                        placeholder="--Enter--"
                        class="w-full"
                      />
              
                      <cornie-input
                        :label="'NAFDAC Registration No.'"
                        v-model="Nafdac"
                        placeholder="--Enter--"
                        class="w-full"
                      />
                      <cornie-select
                        :label="'Classification.'"
                        placeholder="--Select--"
                        :items="[
                          'General Health',
                          'Devices',
                          'Sexual Wellness',
                          'Personal Care',
                          'Nutrition, Fitness & Supplements',
                        ]"
                        v-model="classification"
                      />
                      <cornie-select
                        :label="'Sub-classification.'"
                        placeholder="--Select--"
                        :items="getSubClassify"
                        v-model="subClassification"
                      />
                     <div class="">
                        <span class="flex capitalize mb-5 text-black text-sm font-semibold">
                          Discount applicable?
                        </span>
                        <div class="flex items-end -mb-2">
                          <span class="mr-14"
                            ><cornieradio
                              v-model="applyDiscount"
                              :label="'Yes'"
                              :value="true"
                            />
                          </span>
                          <cornieradio
                            :label="'No'"
                            v-model="applyDiscount"
                            :value="false"
                          />
                        </div>
                      </div>

                  </div>
              </div>  
              <div>
                  <div class="w-full mb-5">
                    <div class="my-4">
                      <cornie-checkbox
                        :label="'This is an inventory item'"
                        v-model="isInventoryItem"
                        :value="'Yes'"
                      />
                    </div>
                  </div>
                  <div class="w-full grid gap-4 grid-cols-3">
                     <cornie-input
                      class="w-full"
                      :label="'Generic Name'"
                      v-model="genericName"
                      :placeholder="'--Enter--'"
                    />
                    <cornie-input
                      class="w-full"
                      :label="'Brand/Manufacturer'"
                      v-model="genericCode"
                      :placeholder="'--Enter--'"
                    />
                      <cornie-input
                        v-model="form"
                        :label="'Form'"
                        :placeholder="'--Enter--'"
                        class="w-full"
                      />
        
                        <cornie-input
                          :label="'Pack'"
                          v-model="pack"
                          placeholder="--Enter--"
                          class="w-full"
                        />
                        <cornie-input
                          :label="'Strength'"
                          v-model="strength"
                          placeholder="--Enter--"
                          class="w-full"
                        />
                        <cornie-input
                          :label="'NAFDAC Registration No.'"
                          v-model="Nafdac"
                          placeholder="--Enter--"
                          class="w-full"
                        />
                         <cornie-input
                            v-model="description"
                            :label="'Description'"
                            placeholder="--Enter--"
                          />
                  </div>
              </div>
              
            </tabs>
          </div>
        </template>
      </accordion-component>

      <div class="w-full my-5" v-if="isInventoryItem">
        <div
          class="stock py-5 cursor-pointer px-2"
          @click="showNewStock = true"
        >
          <p class="flex justify-between px-2 sub-header">
            <span class="text-sm">Stock Unit of Measurement (UoM)</span>
            <span v-if="salesUOMs.length === 0"><add-icon /></span>
            <span v-else><edit-icon class="fill-current text-danger" /></span>
          </p>
        </div>
      </div>
      <accordion-component
        :title="'Cost Information'"
        :opened="false"
        :class="!isInventoryItem ? 'my-5' : ''"
      >
        <template v-slot:default>
          <div class="w-full mb-5 mt-5">
            <div class="mb-2 flex">
              <span
                ><cornieradio
                  :label="'Purchase item'"
                  :value="'purchase'"
                  v-model="purchaseType"
                />
              </span>
              <span class="ml-8"
                ><cornieradio
                  :label="'Non Purchase item'"
                  :value="'non-purchase'"
                  v-model="purchaseType"
                />
              </span>
            </div>
          </div>
          <div class="w-full">
            <div class="w-full">
              <div class="w-full flex ths py-4">
                <div
                  class="th py-4 flex items-center"
                  v-if="purchaseType?.toLowerCase() === 'purchase'"
                >
                  <span class="pl-5">Default</span>
                </div>
                <div
                  class="th py-4 flex items-center"
                  v-if="purchaseType?.toLowerCase() === 'purchase'"
                >
                  <span>Supplier Name</span>
                </div>
                <div class="th py-4 flex items-center">
                  <span
                    :class="{
                      'px-2': purchaseType?.toLowerCase() !== 'purchase',
                    }"
                  >
                    {{
                      purchaseType?.toLowerCase() === "purchase"
                        ? "Purchase UOM"
                        : "UOM"
                    }}
                  </span>
                </div>
                <div class="th py-4 flex items-center">
                  <span>Item Quantity/Unit</span>
                </div>
                <div class="th py-4 flex items-center">
                  <span>Unit Cost (NGN)</span>
                </div>
                <div class="th py-4 flex items-center">
                  <span>Cost per item (NGN)</span>
                </div>
                <div class="th py-4 flex items-center">
                  <span>Available QTY</span>
                </div>
                <div class="th py-4 flex items-center">
                  <span> % availability</span>
                </div>
                <div class="th py-4 flex items-center">
                  <span>weighted av. cost (NGN)</span>
                </div>
              </div>
              <div
                class="w-full flex border border-gray-400"
                :class="
                  suppliers.length - 1 === index
                    ? 'rounded-bl-md rounded-br-md'
                    : ''
                "
                v-for="(supplier, index) in suppliers"
                :key="index"
              >
                <div
                  class="th flex items-center"
                  v-if="purchaseType?.toLowerCase() === 'purchase'"
                >
                  <span class="pl-5"
                    ><cornieradio
                      :value="supplier.id"
                      @update:modelValue="setDefault"
                      name="supplier"
                    />
                  </span>
                </div>
                <div
                  class="th flex items-center"
                  v-if="purchaseType?.toLowerCase() === 'purchase'"
                >
                  <span
                    ><cornie-input
                      v-model="suppliers[index].supplier"
                      :placeholder="'--Enter--'"
                  /></span>
                </div>
                <div class="th flex items-center">
                  <span
                    class="small-text capitalize"
                    :class="{
                      'pl-2': purchaseType?.toLowerCase() !== 'purchase',
                    }"
                    >{{ stocksUnit?.purchase }}</span
                  >
                </div>
                <div class="th flex items-center">
                  <span class="small-text capitalize">{{
                    stocksUnit?.quantity
                  }}</span>
                </div>
                <div class="th flex items-center">
                  <span>
                    <cornie-input
                    v-if="id"
                      v-model="supplier.unitCost"
                      type="text"
                  />
                  <cornie-input
                  v-else
                      v-model="suppliers[index].unitCost"
                      type="text"
                  />
                  </span>
                </div>
                <div class="th flex items-center">
                  <!-- <span><cornie-input v-model="suppliers[index].costPerItem" /></span> -->
                  <span class="small-text capitalize" v-if="id">
                    ₦
                    {{
                      (
                        supplier.unitCost / stocksUnit?.quantity
                      ).toFixed(2)
                    }}
                  </span>
                  <span class="small-text capitalize" v-else>
                    ₦
                    {{
                      (
                        suppliers[index].unitCost / stocksUnit?.quantity
                      ).toFixed(2)
                    }}
                  </span>
                </div>
                <div class="th flex items-center">
                  <span>
                    <cornie-input v-model="supplier.quantity" v-if="id"/>
                    <cornie-input v-model="suppliers[index].quantity" v-else/>
                  </span>
                </div>
                <div class="th flex items-center">
                  <span class="small-text capitalize">
                    {{
                      ((+supplier.quantity / +totalAvailability) * 100).toFixed(2)
                    }}
                  </span>
                </div>
                <div class="th flex items-center">
                  <span class="small-text capitalize" v-if="id">
                    ₦
                    {{
                      (
                        ((supplier.quantity / totalAvailability) * 100) *
                        (supplier.unitCost / stocksUnit?.quantity)
                      ).toFixed(2)
                    }}
                  </span>
                   <span class="small-text capitalize" v-else>
                    ₦
                    {{
                      (
                        ((supplier.quantity / totalAvailability) * 100) *
                        (suppliers[index].unitCost / stocksUnit?.quantity)
                      ).toFixed(2)
                    }}
                  </span>
                </div>
              </div>
            </div>
            <div
              class="w-full my-2"
              v-if="purchaseType?.toLowerCase() === 'purchase'"
            >
              <a
                class="v-xteristics flex cursor-pointer"
                @click="addAnotherSupplier"
              >
                <span class="mr-3"><add-icon /> </span>
                <span>Add Another Supplier</span>
              </a>
            </div>
          </div>
        </template>
      </accordion-component>

      <accordion-component :title="'Sales Information'" :opened="false">
        <template v-slot:default>
          <div class="w-full mt-2 mb-6 flex justify-between">
            <div
              class="w-4/12 p-4"
              style="border: 1px solid #c2c7d6; border-radius: 8px; width: 32%"
            >
              <p class="flex flex-col">
                <span class="sales-label">Weighted Av. Cost (NGN)</span>
                <span class="sales-value">{{ weightedAverageCost }}</span>
              </p>
            </div>
            <div
              class="w-4/12 p-4"
              style="border: 1px solid #c2c7d6; border-radius: 8px; width: 32%"
            >
              <p class="flex flex-col">
                <span class="sales-label">Sales Markup (%)</span>
                <span class="sales-value">{{ PercentageMarkup }}</span>
              </p>
            </div>
            <div
              v-if="applyDiscount == true"
              class="w-4/12 p-4"
              style="border: 1px solid #c2c7d6; border-radius: 8px; width: 32%"
            >
              <p class="flex flex-col">
                <span class="sales-label">Maximum Allowable Discount (%)</span>
                <span class="sales-value">{{ MaxDiscount }}</span>
              </p>
            </div>
          </div>
          <div class="w-full">
            <div class="w-full overflow-x-scroll">
              <div class="w-full flex ths py-2" style="min-width: 1330px">
                <div class="th flex items-center">
                  <span>Sales Unit</span>
                </div>
                <div class="th flex items-center">
                  <span>QTY</span>
                </div>
                <div class="th flex items-center">
                  <span>Item cost</span>
                </div>
                <div class="th flex items-center">
                  <span>Sales markup</span>
                </div>
                <div class="th flex items-center">
                  <span>Item Price</span>
                </div>
                <div class="th flex items-center">
                  <span>margin (ngn)</span>
                </div>
                <div class="th flex items-center">
                  <span>margin (%)</span>
                </div>
                <div class="th flex items-center" v-if="applyDiscount == true">
                  <span>discount limit</span>
                </div>
                <div class="th flex items-center" v-if="applyDiscount == true">
                  <span>Item price (discounted)</span>
                </div>
                <div class="th flex items-center" v-if="applyDiscount == true">
                  <span>DISCOUNTED margin (ngn)</span>
                </div>
                <div class="th flex items-center" v-if="applyDiscount == true">
                  <span>DISCOUNTED margin(%)</span>
                </div>
              </div>
              <div class="w-full flex tbs py-2"  v-for="(sale, index) in salesUOMs"
                  :key="index" style="min-width: 1330px">
                <div class="th flex items-center">
                  <span class="small-text">{{ sale.unitName }}</span>
                </div>
                <div class="th flex items-center">
                  <span class="small-text">{{ sale.itemQuantity }}</span>
                </div>
                <div class="th flex items-center">
                  <span class="small-text">₦ {{ weightedAverageCost }}</span>
                </div>
                <div class="th flex items-center">
                  <span class="small-text"
                    ><cornie-input v-model="sale.markup"
                  /></span>
                </div>
                <div class="th flex items-center">
                  <span class="small-text"
                    >₦
                    {{
                      ItemPriceNGN
                    }}</span
                  >
                </div>
                <div class="th flex items-center">
                  <span class="small-text"
                    >₦
                    {{
                     marginNGN
                    }}</span
                  >
                </div>
                <div class="th flex items-center">
                  <span class="small-text"
                    >{{
                     marginPercent
                    }}%</span
                  >
                </div>
                <div class="th flex items-center" v-if="applyDiscount == true">
                  <span class="small-text"
                    ><cornie-input v-model="sale.discountLimit"
                  /></span>
                </div>
                <div class="th flex items-center" v-if="applyDiscount == true">
                  <span class="small-text">₦ {{ ItemCostDiscounted }}</span>
                </div>
                <div class="th flex items-center" v-if="applyDiscount == true">
                  <span class="small-text">
                    ₦
                    {{ discountedMarginNGN }}
                  </span>
                </div>
                <div class="th flex items-center" v-if="applyDiscount == true">
                  <span class="small-text">{{ discountedMarginPercent}}%</span>
                </div>
              </div>
            </div>
          </div>

          <div class="w-full my-5">
            <a class="v-xteristics">Tax Information</a>
            <span class="flex mt-4">
              <label class="inline-flex items-center">
                <input
                  type="checkbox"
                  v-model="applyVAT"
                  class="form-radio h-3 w-3"
                  :value="'Apply VAT to this service item'"
                />
                <span class="ml-2 noraml-text text-sm font-normal"
                  >Apply VAT to this service item</span
                >
              </label>
            </span>
          </div>
        </template>
      </accordion-component>

      <accordion-component
        :title="'Inventory Information'"
        :opened="false"
        v-if="isInventoryItem"
      >
        <template v-slot:default>
          <div class="w-full grid gap-4 grid-cols-3 mt-5 mb-3">
            <cornie-input
              v-model="inventory.itemCode"
              :label="'Item Code'"
              placeholder="--Autoloaded--"
            />
            <cornie-input
              :disabled="true"
              placeholder="--Autoloaded--"
              :label="'Item Variant'"
              v-model="inventory.itemVariant"
            />
            <cornie-select
              :label="'Valuation Method'"
              v-model="inventory.valuationMethod"
              :items="['fifo', 'lifo', 'weighted-average']"
              placeholder="--Select--"
            />
            <cornie-input
              :disabled="true"
              :label="'Opening Balance'"
              v-model="inventory.openingBalance"
              placeholder="--Autoloaded--"
            />
            <cornie-input
              :label="'Reorder Level'"
              v-model="inventory.reorderLevel"
              placeholder="Enter"
            />
            <cornie-input
              :label="'Batch No'"
              v-model="inventory.batchNo"
              placeholder="Enter"
            />
            <DatePicker :label="'Expiry Date'" v-model="inventory.expiryDate" />
          </div>
        </template>
      </accordion-component>

      <accordion-component
        :title="'Storage Information'"
        :opened="false"
        v-if="isInventoryItem"
      >
        <template v-slot:default>
          <div class="w-full grid grid-cols-12 gap-5 mt-5">
            <div class="w-full col-span-4">
              <cornie-select
                :label="'Storage Condition'"
                :items="['Excellent', 'Good', 'Fair', 'Bad']"
                v-model="storage.condition"
                placeholder="Enter"
              />
            </div>
            <div class="w-full col-span-4">
              <cornie-select
                :label="'Building'"
                :items="locationsList"
                v-model="storage.locationId"
                placeholder="Enter"
              />
            </div>
            <div class="w-full col-span-4">
              <cornie-input
                :label="'Room #'"
                v-model="storage.room"
                placeholder="Enter"
              />
            </div>
          </div>
          <div class="w-full grid grid-cols-12 gap-5 mt-5 mb-3">
            <div class="w-full col-span-4">
              <cornie-input
                :label="'Shelf #'"
                placeholder="Enter"
                v-model="storage.shelf"
              />
            </div>
            <div class="w-full col-span-4">
              <cornie-input
                :label="'Rack #'"
                v-model="storage.rack"
                placeholder="Enter"
              />
            </div>
            <div class="w-full col-span-4">
              <cornie-input
                placeholder="Enter"
                v-model="storage.bin"
                :label="'Bin'"
              />
            </div>
          </div>
        </template>
      </accordion-component>

      <span class="w-full bg-danger">
        <span class="flex justify-end w-full m4-5">
          <cornie-btn
            class="m-5 px-5 font-semibold rounded-lg"
            style="color: #080056; border: 1px solid #080056"
          >
            Cancel
          </cornie-btn>

          <cornie-btn
            class="bg-danger px-8 text-white my-5 mx-4 font-semibold rounded-lg"
            @click="apply"
            :loading="loading"
          >
            Save
          </cornie-btn>
        </span>
      </span>
    </div>

    <!-- <div style="height: 400px">

        </div> -->
    <side-modal
      :visible="showNewVariant"
      :header="'Variant Characteristics'"
      :width="600"
      @closesidemodal="() => (showNewVariant = false)"
    >
      <new-variant
        @added="variantAdded"
        @closesidemodal="() => (showNewVariant = false)"
      />
    </side-modal>

    <stock-unit
      v-model="showNewStock"
      :returnedStock="salesUnit"
      :salesUOMs="salesUOMs"
      @added-stockunit="stockAdded"
      :id="id"
    />
  </div>
</template>

<script lang="ts">
import { Options, Vue, setup } from "vue-class-component";
import { Prop, PropSync, Watch } from "vue-property-decorator";
import CollapseSection from "./dropdown.vue";
import CornieInput from "@/components/cornieinput.vue";
import CornieSelect from "@/components/cornieselect.vue";
import CornieRadio from "@/components/cornieradio.vue";
import Cornieradio from "@/views/dashboard/ehr/progressnotes/cornieradio.vue";
import AddIcon from "@/components/icons/add-orange.vue";
import EditIcon from "@/components/icons/edit.vue";
import CornieCheckbox from "@/components/custom-checkbox.vue";
import DatePicker from "@/components/datepicker.vue";
import Avatar from "@/components/avatar.vue";
import { useHandleImage } from "@/composables/useHandleImage";
import SideModal from "@/views/dashboard/schedules/components/side-modal.vue";
import NewVariant from "./new-variant.vue";
import StockUnit from "./stockUnitMeasurement.vue";
import AccordionComponent from "@/components/form-accordion.vue";
import DeleteRed from "@/components/icons/delete-red.vue";

import {
  ICatalogueProduct,
  IInventory,
  IIStorage,
  IProductVariant,
  IProductStock,
} from "@/types/ICatalogue";
import { namespace } from "vuex-class";
import ILocation from "@/types/ILocation";
import IPractitioner from "@/types/IPractitioner";
import { cornieClient } from "@/plugins/http";
import AutoComplete from "@/components/autocomplete.vue";
import IPracticeform from "@/types/IPracticeform";
import Tabs from "@/components/tabs.vue";


const location = namespace("location");
const catalogue = namespace("catalogues");
const markup = namespace("markup");
const account = namespace("user");
const org = namespace("organization");
const practitioner = namespace("practitioner");
const practiceform = namespace("practiceform");

@Options({
  components: {
    CollapseSection,
    DeleteRed,
    CornieInput,
    CornieSelect,
    CornieRadio,
    Cornieradio,
    AccordionComponent,
    AddIcon,
    CornieCheckbox,
    DatePicker,
    Avatar,
    SideModal,
    NewVariant,
    StockUnit,
    AutoComplete,
    EditIcon,
    Tabs,
  },
})
export default class NewProuct extends Vue {
  @Prop({ type: String, default: "" })
  id!: string;

  markups = [] as any;

  @location.State
  locations!: ILocation[];

  @location.Action
  fetchLocations!: () => Promise<void>;

  @catalogue.Action
  createProduct!: (data: ICatalogueProduct) => Promise<boolean>;

  @catalogue.Action
  getProductsById!: (id: string) => Promise<ICatalogueProduct>;

  @org.State
  organizationInfo!: any;

  @org.Action
  fetchOrgInfo!: () => Promise<void>;

  @account.Getter
  authCurrentLocation!: string;

  @account.Getter
  cornieUser!: any;

  @practitioner.State
  practitioners!: IPractitioner[];

  @practitioner.Action
  fetchPractitioners!: () => Promise<void>;

  @practiceform.State
  practiceforms!: IPracticeform[];

  @practiceform.Action
  fetchPracticeforms!: () => Promise<void>;

  isInventoryItem = "";
  searchresult = [] as any;
  fullInfo = [] as any;
  fullBrand = [] as any;
  fullStrength = [] as any;
  fullPack = [] as any;

  Nafdac = "";
  form = "";
  pack = "";
  strength = "";
  type = "medication";
  genericName = "";
  brandCode = "";
  description = "description";
  genericCode = "genericCode";
  size = "";
  brand = "";
  classification = "";
  subClassification = "";
  category = "";
  ingredientStatus = "";
  ingredient = "";
  regNo = "";
  itemCode = "";
  applyVAT = true;
  applyDiscount = false;
  status = "active";

  dataCode = "";
  dataBrand = "";
  dataForm = "";

  storage = {
    locationId: "",
    room: "",
    rack: "",
    bin: "",
    condition: "",
    shelf: "",
  } as any;
  inventory = {
    itemCode: "",
    valuationMethod: "",
    openingBalance: 0,
    reorderLevel: 0,
    batchNo: "",
    expiryDate: "",
    itemVariant: "",
  } as any;

  inventoryUOM = {
    unitName: "",
    itemQuantity: 0,
  } as any;
  purchaseUOM = {
    unitName: "",
    itemQuantity: 0,
  } as any;

  stocksUnit = {
    purchase: "",
    quantity: "",
    inventory: "",
    itemInventory: "",
    sales: "",
    itemSales: "",
  } as any;
  salesUnit = {
    purchase: "",
    quantity: "",
    inventory: "",
    itemInventory: "",
    sales: "",
    itemSales: "",
  } as any;
  purchaseType = "purchase";

  reqBody = {
    type: "medication",
    purchaseType: "purchase",
    variants: [] as IProductVariant[],
    inventory: {} as IInventory,
    storage: {} as IIStorage,
    status: "active",
    form: "" as any,
  } as ICatalogueProduct;

  tabLinks = [
    "Medications",
    "Other Healthcare Products",
    "Substance",
  ];
  currentTab = 0;

  salesUOMs = [] as any;


  suppliers = [] as any;

  sales = [
    {
      unitName: "Carton",
      itemQuantity: 900,
      markup: 0,
      discountLimit: 0,
    },
    {
      unitName: "Pack",
      itemQuantity: 90,
      markup: 0,
      discountLimit: 0,
    },
    {
      unitName: "Card",
      itemQuantity: 30,
      markup: 0,
      discountLimit: 0,
    },
  ] as any[];
  costInformationType = "";

  get reqbodyType() {
    return this.reqBody.type;
  }

  @Watch("reqbodyType")
  resetVariants() {
    if (this.reqBody.type === "other") this.reqBody.variants = [];
  }

  img = setup(() => useHandleImage());
  showNewVariant = false;
  showNewStock = false;
  loading = false;

  get authLocation() {
    return this.authCurrentLocation;
  }

  get locationsList() {
    if (this.locations?.length <= 0) return [];
    return this.locations?.map((location) => {
      return {
        code: location.id,
        display: location.name,
      };
    });
  }

  get currentPurchaseType() {
    return this.purchaseType;
  }

  deleteItem(id: any) {
    this.reqBody.variants = this.reqBody.variants.filter(
      (item: IProductVariant) => item.id !== id
    );
  }

  get totalAvailability() {
    let total = this.suppliers.reduce(
      (acc: any, item: any) => (acc += +item.quantity),
      0
    );
    return total;
  }

  get ItemPriceNGN() {
    let total = 0;
    for (let i = 0; i < this.salesUOMs.length; i++) {
      total += (+this.weightedAverageCost + ((+this.salesUOMs[i].markup * +this.weightedAverageCost) / 100));
    }

    return total.toFixed(2);
  }
  get marginNGN() {
    let total = 0;
    for (let i = 0; i < this.suppliers.length; i++) {
      total +=
        +this.ItemPriceNGN - +this.weightedAverageCost;
    }

    return total.toFixed(2);
  }

  get marginPercent() {
    let total = 0;
    for (let i = 0; i < this.suppliers.length; i++) {
      total += (+this.marginNGN / +this.ItemPriceNGN) * 100;
    }

    return total.toFixed(2);
  }
   get ItemCostDiscounted() {
    let total = 0;
    for (let i = 0; i < this.salesUOMs.length; i++) {
      total += +this.ItemPriceNGN - ((+this.salesUOMs[i].discountLimit * +this.ItemPriceNGN) / 100);
    }

    return total.toFixed(2);
  }
  get discountedMarginNGN() {
    let total = 0;
    for (let i = 0; i < this.suppliers.length; i++) {
      total += +this.ItemCostDiscounted - +this.weightedAverageCost;
    }

    return total.toFixed(2);
  }
  get discountedMarginPercent() {
    let total = 0;
    for (let i = 0; i < this.suppliers.length; i++) {
      total += (+this.discountedMarginNGN / +this.ItemCostDiscounted) * 100;
    }

    return total.toFixed(2);
  }

  get weightedAverageCost() {
    let total = 0;
    for (let i = 0; i < this.suppliers.length; i++) {
      total +=
        ((this.suppliers[i].quantity / this.totalAvailability) *
          100 *
          (this.suppliers[i].unitCost / this.stocksUnit?.quantity)) /
        this.suppliers.length;
    }

    return total.toFixed(2);
  }
  get costPerItem() {
    let total = 0;
    for (let i = 0; i < this.suppliers.length; i++) {
      total += (+this.suppliers[i].unitCost / +this.stocksUnit?.quantity)
    }

    return total.toFixed(2);
  }  
  get totalAvailabiltyPercent(){
    let total = 0;
    for (let i = 0; i < this.suppliers.length; i++) {
      total += ((+this.suppliers[i].quantity / +this.totalAvailability) * 100)
    }

    return total.toFixed(2);
  }          
  get singleweightedAverageCost() {
    let total = 0;
    for (let i = 0; i < this.suppliers.length; i++) {
      total += +this.costPerItem * +this.totalAvailabiltyPercent
    }

    return total.toFixed(2);
  }
 

 

  get getSubClassify() {
    if (this.classification == "General Health") {
      return [
        "Pain Relief",
        "Cold & Cough",
        "Malaria Care",
        "Bone, Joint & Muscular Care",
        "Eye Care",
        "Ear Care",
        "Hypertensive Care",
        "Respiratory Care",
        "Diabetic Care",
        "Digestive Care",
        "Cholesterol Care",
        "Prostrate Health",
        "STDs & Sexual Care",
        "Piles, Fissures & Fistula",
        "Mental Health",
      ];
    } else if (this.classification == "Devices") {
      return [
        "Masks (N95, Surgical and more)",
        "Face Shield",
        "Surgical Masks",
        "N95 Masks",
        "BP Monitors",
        "Nebulizers & Vaporizers",
        "Oximeters & Pedometers",
        "Vital Signs Monitors & Wearables",
        "Oxygen Concentrators & Cans",
        "Weighing Scales",
        "Thermometers",
        "IR Thermometers",
        "Body Massager",
        " Diabetes Monitors",
        "Test Strips & Lancets",
        "Syringes & Pens",
        "Mobility Equipments",
        "Exercise Equipments",
        "Practice",
        "Stethoscopes",
        "Tapes & Bandages",
        "Clinical Diagnostic Equipments",
        "Dressings & Wound Care",
        "Supports & Braces",
        "Neck & Shoulder Support",
        "Knee & Leg Support",
        "Back & Abdomen Support",
        "Ankle & Foot Support",
        "Hand & Wrist Braces",
        "Arm & Elbow Support",
        "Cervical Pillows",
        "Compression support & sleeves",
        "Heel support",
      ];
    } else if (this.classification == "Sexual Wellness") {
      return [
        "Family Planning & Condoms",
        "Lubricants & Massage Gels",
        "Men Performance Enhancers",
        "Erectile Dysfunction",
        "Fertility Support",
        "Sex Toys",
        "Sexual Health Supplements",
        "Tests & Diagnostics",
      ];
    } else if (this.classification == "Personal Care") {
      return [
        "Skin Care",
        "Hair Care",
        "Oral Care",
        "Baby Care",
        "Elderly Care",
        "Women Care",
        "Men Care",
        "Family Care",
      ];
    } else if (this.classification == "Nutrition, Fitness & Supplements") {
      return [
        "Vitamins & Mineral Supplements",
        "Protein Supplements",
        "Omega & Fish Oil",
        "Pregnancy & Breastfeeding",
        "Immunity Boosters",
        "Sleep Aid",
        "Weight Management",
        "Specialty Supplements",
        "Nutritional Drinks",
        "Other Health Food & Drinks",
      ];
    } else {
      return [
        "Pain Relief",
        "Cold & Cough",
        "Malaria Care",
        "Bone, Joint & Muscular Care",
        "Eye Care",
        "Ear Care",
        "Hypertensive Care",
        "Respiratory Care",
        "Diabetic Care",
        "Digestive Care",
        "Cholesterol Care",
        "Prostrate Health",
        "STDs & Sexual Care",
        "Piles, Fissures & Fistula",
        "Mental Health",
      ] as any[];
    }
  }
  addAnotherSupplier() {
    this.suppliers.push({
      id: Math.random() * 1999 + Math.random() * 2999,
      type: this.purchaseType,
      unitCost: 0,
      quantity: 0,
      supplier: "",
      default: false,
      costPerItem: 0,
      locationId: this.authLocation,
    });
  }

  variantAdded(variant: IProductVariant) {
    this.reqBody.variants?.push(variant);
  }

  stockAdded(stock: any,  salesstock: any) {
    this.stocksUnit = stock;
    this.purchaseUOM.unitName = stock.purchase;
    this.purchaseUOM.itemQuantity = stock.quantity;
    this.inventoryUOM.unitName = stock.inventory;
    this.inventoryUOM.itemQuantity = stock.itemInventory;


    this.salesUnit = {
      purchase: this.purchaseUOM.unitName,
      quantity: this.purchaseUOM.itemQuantity,
      inventory: this.inventoryUOM.unitName,
      itemInventory: this.inventoryUOM.itemQuantity,
      sales: this.stocksUnit.sales,
      itemSales: this.stocksUnit.itemSales,
    };
    if (this.suppliers.length === 0) {
      this.suppliers.push({
        id: Math.random() * 1999 + Math.random() * 2999,
        type: this.purchaseType,
        unitCost: 0,
        quantity: 0,
        supplier: "",
        default: false,
        costPerItem: 0,
        locationId: this.authLocation,
      });
    }
    this.salesUOMs = salesstock;
   
    // this.suppliers.push(
    //   {
    //   id: Math.random() * 1999 + Math.random() * 2999,
    //   type: this.purchaseType,
    //   unitCost: 0,
    //   quantity: 0,
    //   supplier: "",
    //   default: false,
    //   costPerItem: 0,
    //   locationId: this.authLocation,
    // })
  }
  
  get aBrandName(){
    const pt = this.allName.find((i: any) => i.code === this.dataCode);
    return pt ? `${pt.display}` : "";
  }
  get aBrandCode(){
    const pt = this.fullInfo.find((i: any) => i.id === this.dataBrand);
    return pt ? `${pt.name}` : "";
  }

  @Watch("id")
  idChanged() {
    this.setProducts();
  }
  async setProducts() {
    const product = await this.getProductsById(this.id);
    if (!product) return;
    this.img.url = product.image;
    this.category = product.category;
    this.dataCode = product.brand;
    this.dataCode = product.genericName;
    this.dataForm = product.form;
    this.dataBrand = product.brandCode;
    this.brandCode = product.brandCode;
    this.form = product.form;
    this.classification = product.classification;
    this.subClassification = product.subClassification;
    this.applyDiscount = product.applyDiscount;
    this.type = product.type;
    this.genericName = product.genericName;
    this.status = product.status;
    this.brand = product.brand;
    this.ingredient = product.ingredient;
    this.ingredientStatus = product.ingredientStatus;
    this.description = product.description;
    this.size = product.size;
    this.inventoryUOM = product.inventoryUOM;
    this.purchaseUOM = product.purchaseUOM;
    this.suppliers = product.costInformation;
    this.applyVAT = product.applyVAT;
    this.inventory = product.inventory;
    this.storage = product.storage;
    this.Nafdac = product.regNo;
    this.salesUOMs = product.salesUOMs;
   this.strength = product.strength;
   this.salesUnit.purchase = product.purchaseUOM.unitName;
    this.salesUnit.quantity = product.purchaseUOM.itemQuantity;
   this.salesUnit.inventory = product.inventoryUOM.unitName;
    this.salesUnit.itemInventory = product.inventoryUOM.unitName;
   // this.salesUnit.sales = product.purchaseUOM.unitName;
   //this.salesUnit.purchase = product.purchaseUOM.unitName;

   this.stocksUnit.purchase = product.purchaseUOM.unitName;
    this.stocksUnit.quantity = product.purchaseUOM.itemQuantity;
   this.stocksUnit.inventory = product.inventoryUOM.unitName;
    this.stocksUnit.itemInventory = product.inventoryUOM.unitName;
  //  this.stocksUnit.sales = product.purchaseUOM.unitName;
  // this.stocksUnit.purchase = product.purchaseUOM.unitName;


   
  }

  get payload() {
    return {
      genericCode: this.aBrandCode,
      brandCode: this.aBrandCode,
      form: this.allGenericForm,
      classification: this.classification,
      subClassification: this.subClassification,
      applyDiscount: this.applyDiscount,
      type: this.type,
      category: this.category,
      genericName: this.aBrandName,
      status: this.status,
      brand: this.aBrandCode,
      ingredient: this.ingredient,
      ingredientStatus: this.ingredientStatus,
      description: this.description,
      size: this.size,
      inventoryUOM: this.inventoryUOM,
      purchaseUOM: this.purchaseUOM,
      salesUOMs: this.salesUOMs,
      costInformation: this.suppliers,
      applyVAT: this.applyVAT,
      inventory: this.inventory,
      storage: this.storage,
      regNo: this.Nafdac,
      strength: this.strength,


      
    };
  }
  async apply() {
    this.loading = true;
    if (this.id) await this.updateProduct();
    else await this.createProductInventory();
    this.loading = false;
  }
  async createProductInventory() {
    try {
      const response = await cornieClient().post(
        "/api/v1/catalogue-product",
        this.payload
      );
      if (response.success) {
        window.notify({
          msg: "Catalogue product created",
          status: "success",
        });
        this.$router.go(-1);
      }
    } catch (error: any) {
      window.notify({
        msg: error.response.data.message,
        status: "error",
      });
    }
  }
  async updateProduct() {
    const url = `/api/v1/catalogue-product/${this.id}`;
    const payload = {
      ...this.payload,
    };
    try {
      const response = await cornieClient().put(url, payload);
      if (response.success) {
        window.notify({ msg: "Catalogue product  updated", status: "success" });
        this.$router.go(-1);
      }
    } catch (error: any) {
      window.notify({ msg: error.response.data.message, status: "error" });
    }
  }

  async onSave() {
    try {
      this.loading = true;
      if (this.img?.url) {
        this.reqBody.image = this.img.url;
      }
      this.reqBody.costInformation = this.suppliers.map((i: any) => {
        i.type = this.purchaseType;
        return i;
      });

      this.reqBody.salesUOMs = this.sales;
      const created = await this.createProduct(this.reqBody);

      if (created) {
        window.notify({
          msg: `Prodcut ${this.reqBody?.id ? "updated" : "saved"} successfully`,
          status: "success",
        });
        this.$router.go(-1);
      } else {
        window.notify({
          msg: "There was an error, please check the form and try again",
          status: "error",
        });
      }
      this.loading = false;
    } catch (error) {
      this.loading = false;
      window.notify({
        msg: "There was an error, please check the form and try again",
        status: "error",
      });
    }
  }

  setDefault(val: any) {
    this.suppliers.forEach((item: any) => (item.default = false));

    this.suppliers.forEach((item: any) => {
      if (item.id === val) item.default = true;
    });
  }

  SUC = 1000;
  PercentageMarkup = 200;
  MaxDiscount = 10;

  get isRoot() {
    let isRoot = Boolean(
      this.organizationInfo?.rootUserId === this.cornieUser?.id
    );

    return isRoot;
  }
  get CDM() {
    return this.SUC * (this.PercentageMarkup / 100);
  }

  get minimumPrice() {
    return Math.abs(this.CDM * (1 - this.MaxDiscount));
  }

  locationId = null;

  async fetchMarkups() {
    if (this.isRoot) {
      const markups = await cornieClient().get("/api/v1/markup-discount");
      const response = await Promise.all([markups]);
      this.markups = response[0].data as any;

      this.MaxDiscount = this.markups[0]?.maxAllowedDiscount;
      this.PercentageMarkup = this.markups[0]?.markupPercentage;
    } else {
      if (!this.locationId) return [];
      const markups = await cornieClient().get(
        `/api/v1/markup-discount/location/${this.locationId}`
      );
      const response = await Promise.all([markups]);

      this.markups = response[0].data;

      this.MaxDiscount = this.markups[0]?.maxAllowedDiscount;
      this.PercentageMarkup = this.markups[0]?.markupPercentage;
    }

    this.sales.forEach(
      (item: any) => (item.markup = this.PercentageMarkup || 200)
    );
  }

  // get markupItems() {
  //   const markups = this.locations.map((loc: any) => {
  //     let cdm = this.SUC * (this.markups?.markupPercentage / 100);
  //     let margin = Math.abs(cdm - this.SUC);
  //     let percentageMargin = (margin / cdm) * 100;
  //     let minimumPrice = Math.abs(cdm * (1 - this.markups?.maxAllowedDiscount));
  //     let discountMargin = Math.abs(minimumPrice - this.SUC);
  //     let discountMarginPercentage = Math.floor(
  //       (discountMargin / minimumPrice) * 100
  //     );

  //     return {
  //       location: loc.name,
  //       sampleUnitCost: this.SUC,
  //       markupPercentage: this.markups?.markupPercentage,
  //       cdmPrice: cdm,
  //       margin: margin,
  //       marginPercentage: percentageMargin,
  //       maxAllowedDiscount: this.markups?.maxAllowedDiscount,
  //       minPrice: minimumPrice,
  //       discountedMargin: discountMargin,
  //       discountedMarginPercentage: discountMarginPercentage,
  //     };
  //   });

  //   return markups;
  // }

  async fetchLocation() {
    const AllLocation = cornieClient().get(
      "/api/v1/location/myOrg/getMyOrgLocations"
    );

    const response = await Promise.all([AllLocation]);

    if (!this.isRoot) {
      if (!this.locationId) return [];

      response[0].data.forEach((item: any) => {
        if (item.id === this.locationId) {
          this.locations = [item];
        }
      });
    } else {
      this.locations = response[0].data;
    }
  }

  get allName() {
    if (!this.searchresult || this.searchresult.length === 0) return [];
    return this.searchresult.map((i: any) => {
      return {
        code: i.generic_id,
        value: i.generic_id,
        display: i.generic_name,
      };
    });
  }

  get allBrand() {
    if (!this.fullInfo || this.fullInfo.length === 0) return [];
    return this.fullInfo.map((i: any) => {
      return {
        code: i.id,
        value: i.id,
        display: i.name,
      };
    });
  }

  get allForms() {
    if (!this.fullBrand || this.fullBrand.length === 0) return [];
    return this.fullInfo.map((i: any) => {
      return {
        code: i.id,
        value: i.id,
        display: i.form,
      };
    });
  }

  async searchData(event: any) {
    const AllNotes = cornieClient().get(`/api/v1/emdex/generic-by-keyword/`, {
      keyword: event.target.value,
    });
    const response = await Promise.all([AllNotes]);
    if (response[0].data === 0) {
      this.searchresult = "No medication code found";
    } else {
      this.searchresult = response[0].data;
    }
  }

  async resultData(id: any) {
    const AllNotes = cornieClient().get(`/api/v1/emdex/generic-brands/${id}`);
    const response = await Promise.all([AllNotes]);
    if (response[0].data === 0) {
      this.fullInfo = "No medication code found";
    } else {
      this.fullInfo = response[0].data;
    }
  }

  get allGenericName() {
    const pt = this.fullInfo.find((i: any) => i.genericId === this.dataCode);
    return (this.genericName = pt ? pt.name : "");
  }
  get allGenericCode() {
    const pt = this.fullInfo.find((i: any) => i.id === this.dataBrand);
    return (this.genericCode = pt ? pt.name : "");
  }
  get allGenericForm() {
    const pt = this.fullInfo.find((i: any) => i.id === this.dataForm);
    return (this.form = pt ? pt.form : "");
  }


  async resultBrand(id: any) {
    const pt = this.fullInfo.find((i: any) => i.id === id);
    return (this.fullBrand = pt ? pt.form : {});
  }
  async resultPack(id: any) {
    console.log(id, "NAFADAC dataCode");
    const pt = this.fullInfo.find((i: any) => i.id === id);
    this.resultStrength(id);
    this.size = pt.pack;
    return (this.pack = pt  ? `${pt?.pack}` : "Pack not available");
  }

  async resultStrength(id: any) {
    const pt = this.fullInfo.find((i: any) => i.id === id);
    this.resultNadac(id);

    return (this.strength = pt ? `${pt?.strength}` : "Strength not available");
  }
  async resultNadac(id: any) {
    const pt = this.fullInfo.find((i: any) => i.id === id);
    return (this.Nafdac = pt ? `${pt?.NAFDAC}` : "NAFDAC not available");
  }

  async created() {
    await this.setProducts();
    if (!this.organizationInfo) await this.fetchOrgInfo();

    await this.fetchMarkups();
    await this.fetchPracticeforms();

    if (!this.isRoot) {
      if (!this.practitioners.length) await this.fetchPractitioners();
      let currentPractiotioner = this.practitioners.find(
        (item: any) => item?.userId === this.cornieUser?.id
      );

      currentPractiotioner?.locationRoles?.forEach((item: any) => {
        if (!item.default) {
          this.locationId = item.locationId;
        }
      });
    }
    await this.fetchLocation();

    if (this.locations?.length <= 0) await this.fetchLocations();
  }
}
</script>

<style scoped>
.v-xteristics {
  font-style: normal;
  font-weight: 600;
  font-size: 14px;
  line-height: 21px;
  color: #fe4d3c;
}

.stock {
  background: #ffffff;
  /* Buttons & Cards */
  box-shadow: 0px 1px 2px rgba(46, 41, 78, 0.02),
    0px 4px 8px rgba(46, 41, 78, 0.08);
  border-radius: 8px;
}

.sub-header {
  font-style: normal;
  font-weight: bold;
  font-size: 18px;
  line-height: 22px;
  color: #14171f;
}

.th {
  font-style: normal;
  font-weight: bold;
  font-size: 12px;
  line-height: 19px;
  letter-spacing: 0.02em;
  text-transform: uppercase;
  color: #080056;
  min-width: 120px;
  width: 16.6%;
  padding: 0.55rem 0.25rem;
}

.ths {
  background: #f0f4fe;
  border-radius: 8px 8px 0px 0px;
  padding: 0.25rem;
}

.tbs {
  background: #ffffff;
  border: 1px solid #c2c7d6;
  box-sizing: border-box;
  border-radius: 0px 0px 8px 8px;
}

.small-text {
  font-style: normal;
  font-weight: normal;
  font-size: 14px;
  line-height: 20px;
  color: #14171f;
}

.sales-value {
  font-style: normal;
  font-weight: bold;
  font-size: 18px;
  line-height: 27px;
  color: #141f15;
}

.sales-label {
  font-style: normal;
  font-weight: normal;
  font-size: 14px;
  line-height: 20px;
  color: #667499;
}

.small-text {
  font-style: normal;
  font-weight: normal;
  font-size: 14px;
  line-height: 20px;
  color: #14171f;
}

input[type="checkbox"]:after {
  border: 1px solid #c4bdbd !important;
}
input[type="checkbox"]:checked:after {
  background-color: #ff0000 !important;
}
</style>
