<template>
  <div class="p-2">
    <div>
       <accordion-component
          v-if="!$route.path.includes('variant')"
          title="New Product"
          :opened="true"
         >
          <template v-slot:default>
            <div class="w-full mb-5">
              <div class="my-4">
                <cornie-checkbox
                  :label="'This is an inventory item'"
                  v-model="isInventoryItem"
                />
              </div>
              <p class="v-xteristics mb-4">Select Product Type</p>
              <div class="my-2 flex">
                <span
                  ><cornieradio
                    v-model="type"
                    :label="'Medication Product'"
                    :value="'medication'"
                  />
                </span>
                <span class="ml-8"
                  ><cornieradio
                    v-model="type"
                    :label="'Other Health Product'"
                    :value="'other'"
                  />
                </span>
              </div>
            </div>

            <div
              class="grid grid-cols-3 gap-4"
              v-if="type?.toLowerCase() === 'medication'"
            >
                <auto-complete class="w-full" :label="'Generic Name'" :items="allName" @click="resultData(dataCode)" @input="searchData"  v-model="dataCode" :placeholder="'Select'"/>
            
                <cornie-select class="w-full" :label="'Brand/Manufacturer'"  :items="allBrand" @click="resultBrand(dataBrand)"  v-model="dataBrand" :placeholder="'Select'"/>
                <cornie-select
                  v-model="dataForm"
                  :label="'Form'"
                  :items="allForms"
                  :placeholder="'Select'"
                  class="w-full"
                  @click="resultPack(dataForm)"
                /> 
                <cornie-input
                  :label="'Pack'"
                  v-model="pack"
                  placeholder="--Autoloaded--"
                  class="w-full"
                  :disabled="true"
                />
                 <cornie-input
                  :label="'Strength'"
                  v-model="strength"
                  placeholder="--Autoloaded--"
                  class="w-full"
                  :disabled="true"
                />  
                <cornie-input
                  :label="'NAFDAC Registration No.'"
                  v-model="Nafdac"
                  placeholder="--Autoloaded--"
                  class="w-full"
                  :disabled="true"
                />
                <cornie-select
                  :label="'Classification.'"
                  placeholder="--Enter--"
                  :items="['General Health','Devices','Sexual Wellness','Personal Care','Nutrition, Fitness & Supplements']"
                  v-model="classification"
                />
                <cornie-select
                  :label="'Sub-classification.'"
                  placeholder="--Enter--"
                  :items="getSubClassify"
                  v-model="subClassification" />
            
                <cornie-select
                  v-model="category"
                  :label="'Category'"
                  :items="['Option 1']"
                />
  
                <div class="">
                  <span class="flex capitalize mb-5 text-black text-sm font-semibold">
                    Discount applicable?
                  </span>
                  <div class="flex items-end -mb-2">
                    <span class="mr-14"><cornieradio
                        v-model="applyDiscount"
                        :label="'Yes'"
                        :value="true"/>
                    </span>
                    <cornieradio
                      :label="'No'"
                      v-model="applyDiscount"
                      :value="false"
                    />
                  </div>
                </div>
               <cornie-input
                    v-model="itemCode"
                    :label="'Item Code'"
                    placeholder="Autogenerated"
                  />
            </div>

            <div
              class="w-full grid gap-4 grid-cols-3"
              v-if="type?.toLowerCase() === 'other'"
            >
                <cornie-input
                  :label="'Classification.'"
                  v-model="classification"
                  placeholder="--Enter--"
                />
                <cornie-input
                  :label="'Sub-classification.'"
                  v-model="subClassification"
                  placeholder="--Enter--"
                />
                <auto-complete class="w-full" :label="'Generic Name'" :items="allName" @click="resultData(dataCode)" @input="searchData"  v-model="dataCode" :placeholder="'Select'"/>
            
                <cornie-select class="w-full" :label="'Brand/Manufacturer'"  :items="allBrand" @click="resultBrand(brandCode)"  v-model="brandCode" :placeholder="'Select'"/>
                <cornie-select
                  v-model="form"
                  :label="'Form'"
                  :items="allForms"
                  :placeholder="'Select'"
                  class="w-full"
                  @click="resultPack(dataForm)"
                /> 
                <cornie-input
                  :label="'Pack'"
                  v-model="pack"
                  placeholder="--Autoloaded--"
                  class="w-full"
                  :disabled="true"
                />
                 <cornie-input
                  :label="'Strength'"
                  v-model="strength"
                  placeholder="--Autoloaded--"
                  class="w-full"
                  :disabled="true"
                />  
                <cornie-input
                  :label="'NAFDAC Registration No.'"
                  v-model="Nafdac"
                  placeholder="--Autoloaded--"
                  class="w-full"
                  :disabled="true"
                />
                <cornie-select
                  v-model="category"
                  :label="'Category'"
                  :items="['Option 1']"
                />
                <cornie-input
                  v-model="itemCode"
                  :label="'Item Code'"
                  placeholder="Autogenerated"
                />
              <!-- <div class="w-full col-span-4">
                <cornie-input
                  v-model="reqBody.ingredient"
                  :label="'Ingrdient'"
                  placeholder="--Autoloaded--"
                />
              </div> -->
              <!-- <div class="w-4/12">
                <cornie-input
                  :label="'Description'"
                  v-model="reqBody.description"
                  placeholder="Enter"
                />
              </div>
              <div
                class="w-4/12"
                v-if="reqBody.type?.toLowerCase() === 'other'"
              >
                <cornie-input
                  :label="'Container | Size'"
                  v-model="reqBody.size"
                  placeholder="Enter"
                />
              </div> -->
            </div>

            <div class="grid grid-cols-4 gap-4" v-if="reqBody.variants.length">
              <div
                class="flex space-x-4 mt-5 border-r-2 border-gray-100 pr-5"
                v-for="(item, index) in reqBody.variants"
                :key="index"
              >
                <div class="flex">
                  <div
                    class="w-10 h-10 rounded-full flex justify-center items-center bg-blue-600 text-white text-lg text-center font-bold mr-2 overflow-hidden"
                  >
                    <img :src="item.image" alt="" class="w-full h-full" />
                  </div>
                  <div>
                    <div class="text-black flex text-sm">
                      <div class="text-black ml-1">
                        {{ item.form }}-{{ item.pack }}
                      </div>
                    </div>
                    <p class="text-xs text-gray-400 mb-1">
                      {{ item.packQuantity }}-{{ item.strength }}
                    </p>
                  </div>
                </div>
                <div class="flex -mt-6 justify-center items-center">
                  <button
                    class="border-0"
                    type="button"
                    @click="deleteItem(item.id)"
                  >
                    <delete-red />
                  </button>
                </div>
              </div>
            </div>
            <!-- End Other -->
          </template>
        </accordion-component>
        <!-- <accordion-component
          v-if="!$route.path.includes('variant')"
          title="New Variant"
          :opened="false"
         >
          <template  v-slot:default>
            <div class="w-full flex items-center mb-3">
              <div class="w-4/12">
                <cornie-select :label="'Form'" :items="['Option 1']" />
              </div>
              <div class="w-4/12">
                <cornie-select :label="'Pack'" :items="['Option 1']" />
              </div>
              <div class="w-4/12">
                <cornie-select :label="'Pack Quantity'" :items="['Option 1']" />
              </div>
            </div>
            <div class="w-full flex items-center my-3">
              <div class="w-4/12">
                <cornie-select :label="'Strength'" :items="['Option']" />
              </div>
              <div class="w-4/12"></div>
              <div class="w-4/12"></div>
            </div>

            <div class="w-full my-6">
              <a
                class="v-xteristics flex cursor-pointer"
                @click="() => (showNewVariant = true)"
              >
                <span class="mr-3"><add-icon /> </span>
                <span>Add New Characteristics</span>
              </a>
            </div>
          </template>
        </accordion-component> -->
   
      <div class="w-full my-5" v-if="isInventoryItem">
        <div
          class="stock py-5 cursor-pointer px-2"
          @click="showNewStock = true"
        >
          <p class="flex justify-between px-2 sub-header">
            <span class="text-sm">Stock Unit of Measurement (UoM)</span>
            <span><add-icon /></span>
          </p>
        </div>
      </div>
       <accordion-component
          :title="'Cost Information'"
          :opened="false"
          :class="!isInventoryItem ? 'my-5' : ''"
        >

          <template v-slot:default>
            <div class="w-full mb-5 mt-5">
              <div class="mb-2 flex">
                <span
                  ><cornieradio
                    :label="'Purchase item'"
                    :value="'purchase'"
                    v-model="purchaseType"
                  />
                </span>
                <span class="ml-8"
                  ><cornieradio
                    :label="'Non Purchase item'"
                    :value="'non-purchase'"
                    v-model="purchaseType"
                  />
                </span>
              </div>
            </div>
            <div class="w-full">
              <div class="w-full">
                <div class="w-full flex ths py-4">
                  <div
                    class="th py-4 flex items-center"
                    v-if="purchaseType?.toLowerCase() === 'purchase'"
                  >
                    <span class="pl-5">Default</span>
                  </div>
                  <div
                    class="th py-4 flex items-center"
                    v-if="purchaseType?.toLowerCase() === 'purchase'"
                  >
                    <span>Supplier Name</span>
                  </div>
                  <div class="th py-4 flex items-center">
                    <span
                      :class="{
                        'px-2':
                          purchaseType?.toLowerCase() !== 'purchase',
                      }"
                    >
                      {{
                        purchaseType?.toLowerCase() === "purchase"
                          ? "Purchase UOM"
                          : "UOM"
                      }}
                    </span>
                  </div>
                  <div class="th py-4 flex items-center">
                    <span>Item Quantity/Unit</span>
                  </div>
                  <div class="th py-4 flex items-center">
                    <span>Unit Cost</span>
                  </div>
                  <div class="th py-4 flex items-center">
                    <span>Cost per item</span>
                  </div>
                  <div class="th py-4 flex items-center">
                    <span>Available QTY</span>
                  </div>
                  <div class="th py-4 flex items-center">
                    <span> % availability</span>
                  </div>
                  <div class="th py-4 flex items-center">
                    <span>weighted av. cost</span>
                  </div>
                </div>
                <div
                  class="w-full flex border border-gray-400"
                  :class="
                    suppliers.length - 1 === index
                      ? 'rounded-bl-md rounded-br-md'
                      : ''
                  "
                  v-for="(supplier, index) in suppliers"
                  :key="index"
                >
                  <div
                    class="th flex items-center"
                    v-if="purchaseType?.toLowerCase() === 'purchase'"
                  >
                    <span class="pl-5"
                      ><cornieradio
                        :value="supplier.id"
                        @update:modelValue="setDefault"
                        name="supplier"
                      />
                    </span>
                  </div>
                  <div
                    class="th flex items-center"
                    v-if="purchaseType?.toLowerCase() === 'purchase'"
                  >
                    <span
                      ><cornie-input
                        v-model="suppliers[index].supplier"
                        :placeholder="'--Enter--'"
                    /></span>
                  </div>
                  <div class="th flex items-center">
                    <span
                      class="small-text capitalize"
                      :class="{
                        'pl-2':
                          purchaseType?.toLowerCase() !== 'purchase',
                      }"
                      >{{ stocksUnit?.inventory }}</span
                    >
                  </div>
                  <div class="th flex items-center">
                    <span class="small-text capitalize">{{
                      stocksUnit?.quantity
                    }}</span>
                  </div>
                  <div class="th flex items-center">
                    <span
                      ><cornie-input v-model="suppliers[index].unitCost" type="text"
                    /></span>
                  </div>
                  <div class="th flex items-center">
                    <span><cornie-input v-model="suppliers[index].costPerItem" /></span>
                  </div>
                  <div class="th flex items-center">
                    <span
                      ><cornie-input v-model="suppliers[index].quantity"
                    /></span>
                  </div>
                  <div class="th flex items-center">
                    <span class="small-text capitalize">
                      {{
                        (
                          (+supplier.quantity / +totalAvailability) *
                          100
                        ).toFixed(2)
                      }}
                    </span>
                  </div>
                  <div class="th flex items-center">
                    <span class="small-text capitalize">
                      {{
                        (
                          (+supplier.quantity / +totalAvailability) *
                          supplier.costPerItem
                        ).toFixed(2)
                      }}
                    </span>
                  </div>
                </div>
              </div>
              <div
                class="w-full my-2"
                v-if="purchaseType?.toLowerCase() === 'purchase'"
              >
                <a
                  class="v-xteristics flex cursor-pointer"
                  @click="addAnotherSupplier"
                >
                  <span class="mr-3"><add-icon /> </span>
                  <span>Add Another Supplier</span>
                </a>
              </div>
            </div>
          </template>
        </accordion-component>

        <accordion-component :title="'Sales Information'" :opened="false">
          <template v-slot:default>
            <div class="w-full mt-2 mb-6 flex justify-between">
              <div
                class="w-4/12 p-4"
                style="
                  border: 1px solid #c2c7d6;
                  border-radius: 8px;
                  width: 32%;
                "
              >
                <p class="flex flex-col">
                  <span class="sales-label">Weighted Av. Cost (NGN)</span>
                  <span class="sales-value">{{ weightedAverageCost }}</span>
                </p>
              </div>
              <div
                class="w-4/12 p-4"
                style="
                  border: 1px solid #c2c7d6;
                  border-radius: 8px;
                  width: 32%;
                "
              >
                <p class="flex flex-col">
                  <span class="sales-label">Sales Markup (%)</span>
                  <span class="sales-value">{{ PercentageMarkup }}</span>
                </p>
              </div>
              <div
                class="w-4/12 p-4"
                style="
                  border: 1px solid #c2c7d6;
                  border-radius: 8px;
                  width: 32%;
                "
              >
                <p class="flex flex-col">
                  <span class="sales-label"
                    >Maximum Allowable Discount (%)</span
                  >
                  <span class="sales-value">{{ MaxDiscount }}</span>
                </p>
              </div>
            </div>
            <div class="w-full">
              <div class="w-full overflow-x-scroll">
                <div class="w-full flex ths py-2" style="min-width: 1330px">
                  <div class="th flex items-center">
                    <span>Sales Unit</span>
                  </div>
                  <div class="th flex items-center">
                    <span>QTY</span>
                  </div>
                  <div class="th flex items-center">
                    <span>service cost</span>
                  </div>
                  <div class="th flex items-center">
                    <span>Sales markup</span>
                  </div>
                  <div class="th flex items-center">
                    <span>Service fee</span>
                  </div>
                  <div class="th flex items-center">
                    <span>margin (ngn)</span>
                  </div>
                  <div class="th flex items-center">
                    <span>margin (%)</span>
                  </div>
                  <div class="th flex items-center">
                    <span>discount limit</span>
                  </div>
                  <div class="th flex items-center">
                    <span>Service fee (discounted)</span>
                  </div>
                  <div class="th flex items-center">
                    <span>DISCOUNTED margin (ngn)</span>
                  </div>
                  <div class="th flex items-center">
                    <span>DISCOUNTED margin(%)</span>
                  </div>
                </div>
                <div
                  class="w-full flex tbs py-2"
                  style="min-width: 1330px"
                  v-for="(sale, index) in salesUOMs"
                  :key="index"
                >
                  <div class="th flex items-center">
                    <span class="small-text">{{ sale.unitName }}</span>
                  </div>
                  <div class="th flex items-center">
                    <span class="small-text">{{ sale.itemQuantity }}</span>
                  </div>
                  <div class="th flex items-center">
                    <span class="small-text">₦ 120,000.00</span>
                  </div>
                  <div class="th flex items-center">
                    <span class="small-text"
                      ><cornie-input v-model="salesUnit[index].markup"
                    /></span>
                  </div>
                  <div class="th flex items-center">
                    <span class="small-text">₦ 240,000.00</span>
                  </div>
                  <div class="th flex items-center">
                    <span class="small-text">₦ 240,000.00</span>
                  </div>
                  <div class="th flex items-center">
                    <span class="small-text">50%</span>
                  </div>
                  <div class="th flex items-center">
                    <span class="small-text"
                      ><cornie-input v-model="salesUnit[index].discountLimit"
                    /></span>
                  </div>
                  <div class="th flex items-center">
                    <span class="small-text">₦ 216,000.00</span>
                  </div>
                  <div class="th flex items-center">
                    <span class="small-text"> ₦ 86,000.00</span>
                  </div>
                  <div class="th flex items-center">
                    <span class="small-text">43%</span>
                  </div>
                </div>
              </div>
            </div>

            <div class="w-full my-5">
              <a class="v-xteristics">Tax Information</a>
              <span class="flex mt-4">
                <label class="inline-flex items-center">
                  <input
                    type="checkbox"
                    v-model="applyVAT"
                    class="form-radio h-3 w-3"
                    :value="'Apply VAT to this service item'"
                  />
                  <span class="ml-2 noraml-text text-sm font-normal"
                    >Apply VAT to this service item</span
                  >
                </label>
              </span>
            </div>
          </template>
        </accordion-component>

        <accordion-component
          :title="'Inventory Information'"
          :opened="false"
           v-if="isInventoryItem"
        >
          <template v-slot:default>
            <div class="w-full grid gap-4 grid-cols-3 mt-5 mb-3">
                <cornie-input
                  v-model="inventory.itemCode"
                  :label="'Item Code'"
                  placeholder="--Autoloaded--"
                />
                <cornie-input
                  :disabled="true"
                  placeholder="--Autoloaded--"
                  :label="'Item Variant'"
                  v-model="inventory.itemVariant"
                />
                <cornie-select
                  :label="'Valuation Method'"
                  v-model="inventory.valuationMethod"
                  :items="['fifo', 'lifo', 'weighted-average']"
                />
                <cornie-input
                  :disabled="true"
                  :label="'Opening Balance'"
                  v-model="inventory.openingBalance"
                  placeholder="--Autoloaded--"
                />
                <cornie-input
                  :label="'Reorder Level'"
                  v-model="inventory.reorderLevel"
                  placeholder="Enter"
                />
                <cornie-input
                  :label="'Batch No'"
                  v-model="inventory.batchNo"
                  placeholder="Enter"
                />
                <DatePicker
                  :label="'Expiry Date'"
                  v-model="inventory.expiryDate"
                />

            </div>
          </template>
        </accordion-component>

        <accordion-component
          :title="'Storage Information'"
           :opened="false"
           v-if="isInventoryItem"
        >
          <template v-slot:default>
            <div class="w-full grid grid-cols-12 gap-5 mt-5">
              <div class="w-full col-span-4">
                <cornie-select
                  :label="'Storage Condition'"
                  :items="['Excellent', 'Good', 'Fair', 'Bad']"
                  v-model="storage.condition"
                  placeholder="Enter"
                />
              </div>
              <div class="w-full col-span-4">
                <cornie-select
                  :label="'Building'"
                  :items="locationsList"
                  v-model="storage.locationId"
                  placeholder="Enter"
                />
              </div>
              <div class="w-full col-span-4">
                <cornie-input
                  :label="'Room #'"
                  v-model="storage.room"
                  placeholder="Enter"
                />
              </div>
            </div>
            <div class="w-full grid grid-cols-12 gap-5 mt-5 mb-3">
              <div class="w-full col-span-4">
                <cornie-input
                  :label="'Shelf #'"
                  placeholder="Enter"
                  v-model="storage.shelf"
                />
              </div>
              <div class="w-full col-span-4">
                <cornie-input
                  :label="'Rack #'"
                  v-model="storage.rack"
                  placeholder="Enter"
                />
              </div>
              <div class="w-full col-span-4">
                <cornie-input
                  placeholder="Enter"
                  v-model="storage.bin"
                  :label="'Bin'"
                />
              </div>
            </div>
          </template>
        </accordion-component>

      <span class="w-full bg-danger">
        <span class="flex justify-end w-full m4-5">
          <cornie-btn
            class="m-5 px-5 font-semibold rounded-lg"
            style="color: #080056; border: 1px solid #080056"
          >
            Cancel
          </cornie-btn>

          <cornie-btn
            class="bg-danger px-8 text-white my-5 mx-4 font-semibold rounded-lg"
            @click="apply"
            :loading="loading"
          >
            Save
          </cornie-btn>
        </span>
      </span>
    </div>

    <!-- <div style="height: 400px">

        </div> -->
    <side-modal
      :visible="showNewVariant"
      :header="'Variant Characteristics'"
      :width="600"
      @closesidemodal="() => (showNewVariant = false)"
    >
      <new-variant
        @added="variantAdded"
        @closesidemodal="() => (showNewVariant = false)"
      />
    </side-modal>

     <stock-unit
        v-model="showNewStock"
        @added-stockunit="stockAdded"
      />
  </div>
</template>

<script lang="ts">
import { Options, Vue, setup } from "vue-class-component";
import { Prop, PropSync, Watch } from "vue-property-decorator";
import CollapseSection from "./dropdown.vue";
import CornieInput from "@/components/cornieinput.vue";
import CornieSelect from "@/components/cornieselect.vue";
import CornieRadio from "@/components/cornieradio.vue";
import Cornieradio from "@/views/dashboard/ehr/progressnotes/cornieradio.vue";
import AddIcon from "@/components/icons/add-orange.vue";
import CornieCheckbox from "@/components/custom-checkbox.vue";
import DatePicker from "@/components/datepicker.vue";
import Avatar from "@/components/avatar.vue";
import { useHandleImage } from "@/composables/useHandleImage";
import SideModal from "@/views/dashboard/schedules/components/side-modal.vue";
import NewVariant from "./new-variant.vue";
import StockUnit from "./stockUnitMeasurement.vue";
import AccordionComponent from "@/components/form-accordion.vue";
import DeleteRed from "@/components/icons/delete-red.vue";

import {
  ICatalogueProduct,
  IInventory,
  IIStorage,
  IProductVariant,
  IProductStock,
} from "@/types/ICatalogue";
import { namespace } from "vuex-class";
import ILocation from "@/types/ILocation";
import IPractitioner from "@/types/IPractitioner";
import { cornieClient } from "@/plugins/http";
import AutoComplete from "@/components/autocomplete.vue";
import IPracticeform from "@/types/IPracticeform";

const location = namespace("location");
const catalogue = namespace("catalogues");
const markup = namespace("markup");
const account = namespace("user");
const org = namespace("organization");
const practitioner = namespace("practitioner");
const practiceform = namespace("practiceform");

@Options({
  components: {
    CollapseSection,
    DeleteRed,
    CornieInput,
    CornieSelect,
    CornieRadio,
    Cornieradio,
    AccordionComponent,
    AddIcon,
    CornieCheckbox,
    DatePicker,
    Avatar,
    SideModal,
    NewVariant,
    StockUnit,
    AutoComplete,
  },
})
export default class NewProuct extends Vue {
  @Prop({ type: String, default: "" })
  id!: string;

  markups = [] as any;


  @location.State
  locations!: ILocation[];

  @location.Action
  fetchLocations!: () => Promise<void>;

  @catalogue.Action
  createProduct!: (data: ICatalogueProduct) => Promise<boolean>;

  @catalogue.Action
  getProductsById!: (id: string) => Promise<ICatalogueProduct>;

  @org.State
  organizationInfo!: any;

  @org.Action
  fetchOrgInfo!: () => Promise<void>;

  @account.State
  currentLocation!: string;

  @account.Getter
  cornieUser!: any;

  @practitioner.State
  practitioners!: IPractitioner[];

  @practitioner.Action
  fetchPractitioners!: () => Promise<void>;

  @practiceform.State
  practiceforms!: IPracticeform[];

  @practiceform.Action
  fetchPracticeforms!: () => Promise<void>;

  isInventoryItem = "";
  searchresult = [] as any;
  fullInfo = [] as any;
  fullBrand = [] as any;
  fullStrength = [] as any;
  fullPack  = [] as any;


  Nafdac = "";
  form = "";
  pack = "";
  strength = "";
  type = "medication";
  genericName = "";
  brandCode = "brandCode";
  description = "description";
  genericCode = "genericCode";
  size = "size";
  brand = "brand";
  classification = "";
  subClassification = "";
  category = "";
  ingredientStatus = "";
  ingredient = "";
  regNo = "";
  itemCode = "";
  applyVAT = true;
  applyDiscount = false;
  status = "active";

  dataCode = "";
  dataBrand = "";
  dataForm = "";

  storage = {
    locationId: "",
    room: "",
    rack: "",
    bin: "",
    condition: "",
    shelf : ""
  } as any;
  inventory = {
    itemCode: "",
    valuationMethod: "",
    openingBalance: 0,
    reorderLevel: 0,
    batchNo: "",
    expiryDate: "",
    itemVariant: "",
  } as any;

  inventoryUOM = {
    unitName: "",
    itemQuantity: 0
  } as any;
  purchaseUOM = {
     unitName: "",
    itemQuantity: 0
  } as any;

  stocksUnit = {} as any;
  salesUnit = [] as any;
  purchaseType = "purchase";


  reqBody = {
    type: "medication",
    purchaseType: "purchase",
    variants: [] as IProductVariant[],
    inventory: {} as IInventory,
    storage: {} as IIStorage,
    status: "active",
    form: "" as any,
  } as ICatalogueProduct;

  salesUOMs = [] as any;

  suppliers = [] as any;

  sales = [
    {
      unitName: "Carton",
      itemQuantity: 900,
      markup: 0,
      discountLimit: 0,
    },
    {
      unitName: "Pack",
      itemQuantity: 90,
      markup: 0,
      discountLimit: 0,
    },
    {
      unitName: "Card",
      itemQuantity: 30,
      markup: 0,
      discountLimit: 0,
    },
  ] as any[];
  costInformationType = "";

  get reqbodyType() {
    return this.reqBody.type;
  }

  @Watch("reqbodyType")
  resetVariants() {
    if (this.reqBody.type === "other") this.reqBody.variants = [];
  }

  img = setup(() => useHandleImage());
  showNewVariant = false;
  showNewStock = false;
  loading = false;

  get authLocation(){
    return this.currentLocation || "";
  }

  get locationsList() {
    if (this.locations?.length <= 0) return [];
    return this.locations?.map((location) => {
      return {
        code: location.id,
        display: location.name,
      };
    });
  }

  get currentPurchaseType() {
    return this.purchaseType;
  }

  @Watch("currentPurchaseType")
  filterSuppliers() {
    // let purchase = this.suppliers.filter(
    //   (item: any) => item.type === "purchase"
    // );
    // let nonPurchase = this.suppliers.filter(
    //   (item: any) => item.type === "non-purchase"
    // );

    // if (this.currentPurchaseType === "purchase") {
    //   this.suppliers = [];
    //   this.suppliers = purchase;
    // } else {
    //   this.suppliers = [];
    //   this.suppliers = nonPurchase;
    // }
    console.log(this.suppliers);
  }

  deleteItem(id: any) {
    this.reqBody.variants = this.reqBody.variants.filter(
      (item: IProductVariant) => item.id !== id
    );
  }

  get totalAvailability() {
    let total = this.suppliers.reduce(
      (acc:any, item: any) => (acc += +item.quantity),
      0
    );
    return total;
  }

  get weightedAverageCost() {
    let total = 0;
    for (let i = 0; i < this.suppliers.length; i++) {
      total +=
        (this.suppliers[i].quantity / this.totalAvailability) *
        this.suppliers[i].costPerItem;
    }

    return total.toFixed(2);
  }

  get getSubClassify(){
    if(this.classification == 'General Health'){
      return [
        'Pain Relief',
        'Cold & Cough',
        'Malaria Care',
        'Bone, Joint & Muscular Care',
        'Eye Care',
        'Ear Care',
        'Hypertensive Care',
        'Respiratory Care',
        'Diabetic Care',
        'Digestive Care',
        'Cholesterol Care',
        'Prostrate Health',
        'STDs & Sexual Care',
        'Piles, Fissures & Fistula',
        'Mental Health',
      ]
    }else if (this.classification == 'Devices'){
      return [
        'Masks (N95, Surgical and more)',
        'Face Shield',
        'Surgical Masks',
        'N95 Masks',
        'BP Monitors',
        'Nebulizers & Vaporizers',
        'Oximeters & Pedometers',
        'Vital Signs Monitors & Wearables',
        'Oxygen Concentrators & Cans',
        'Weighing Scales',
        'Thermometers',
        'IR Thermometers',
        'Body Massager',
       ' Diabetes Monitors',
        'Test Strips & Lancets',
        'Syringes & Pens',
        'Mobility Equipments',
        'Exercise Equipments',
        'Practice',
       'Stethoscopes',
        'Tapes & Bandages',
        'Clinical Diagnostic Equipments',
        'Dressings & Wound Care',
        'Supports & Braces',
        'Neck & Shoulder Support',
        'Knee & Leg Support',
        'Back & Abdomen Support',
        'Ankle & Foot Support',
        'Hand & Wrist Braces',
        'Arm & Elbow Support',
        'Cervical Pillows',
        'Compression support & sleeves',
        'Heel support',
      ]
    }else if (this.classification == 'Sexual Wellness'){
      return [
          'Family Planning & Condoms',
          'Lubricants & Massage Gels',
          'Men Performance Enhancers',
          'Erectile Dysfunction',
          'Fertility Support',
          'Sex Toys',
          'Sexual Health Supplements',
          'Tests & Diagnostics',
      ]
    } else if (this.classification == 'Personal Care'){
      return [
        'Skin Care',
        'Hair Care',
        'Oral Care',
        'Baby Care',
        'Elderly Care',
        'Women Care',
        'Men Care',
        'Family Care',
      ]
    }else if (this.classification == 'Nutrition, Fitness & Supplements'){
      return [
        'Vitamins & Mineral Supplements',
        'Protein Supplements',
        'Omega & Fish Oil',
        'Pregnancy & Breastfeeding',
        'Immunity Boosters',
        'Sleep Aid',
        'Weight Management',
        'Specialty Supplements',
        'Nutritional Drinks',
        'Other Health Food & Drinks',
      ]
    }else {
      return[
        'Pain Relief',
        'Cold & Cough',
        'Malaria Care',
        'Bone, Joint & Muscular Care',
        'Eye Care',
        'Ear Care',
        'Hypertensive Care',
        'Respiratory Care',
        'Diabetic Care',
        'Digestive Care',
        'Cholesterol Care',
        'Prostrate Health',
        'STDs & Sexual Care',
        'Piles, Fissures & Fistula',
        'Mental Health',
      ] as any[];
    }
  }
  addAnotherSupplier() {
    this.suppliers.push({
      id: Math.random() * 1999 + Math.random() * 2999,
      uom: "Carton",
      type: this.purchaseType,
      unitCost: 0,
      supplier: "--Enter--",
      default: "",
      costPerItem: 12,
      quantity: 90,
    });
  }

  variantAdded(variant: IProductVariant) {
    this.reqBody.variants?.push(variant);
  }

  stockAdded(stock: any) {
    this.stocksUnit = stock;
    this.salesUnit.push(stock);
    this.salesUOMs.push(
      {
      unitName: stock.purchase,
      itemQuantity: stock.quantity,
      markup: 0,
      discountLimit: 0
    }
      );
    this.inventoryUOM.unitName = stock.inventory;
    this.inventoryUOM.itemQuantity = stock.itemInventory;
    this.purchaseUOM.unitName = stock.purchase;
    this.purchaseUOM.itemQuantity = stock.quantity; 
    this.suppliers.push(
      {
      id: Math.random() * 1999 + Math.random() * 2999,
      type: this.purchaseType,
      unitCost: 0,
      quantity: 0,
      supplier: "",
      default: false,
      costPerItem: 0,
      locationId: this.authLocation,
    })
  }

  @Watch("id")
  idChanged() {
    this.setProducts();
  }
   async setProducts() {
    const product = await this.getProductsById(this.id);
    if (!product) return;
    this.img.url = product.image;
    this.category = product.category;
    this.genericCode = product.genericCode;
    this.dataCode = product.genericName;
    this.dataForm = product.form;
    this.dataBrand = product.brandCode;
    this.brandCode = product.brandCode;
    this.form = product.form;
    this.classification = product.classification;
    this.subClassification = product.subClassification;
    this.applyDiscount = product.applyDiscount;
    this.type = product.type;
    this.genericName = product.genericName;
    this.status = product.status;
    this.brand = product.brand;
    this.ingredient = product.ingredient;
    this.ingredientStatus = product.ingredientStatus;
    this.description = product.description;
    this.size = product.size;
    this.inventoryUOM = product.inventoryUOM;
    this.purchaseUOM = product.purchaseUOM;
    this.suppliers = product.costInformation;
    this.applyVAT = product.applyVAT;
    this.inventory = product.inventory;
    this.storage = product.storage;
    this.Nafdac = product.regNo;

  }

    get payload() {
        return {
           genericCode: this.genericCode,
            brandCode: this.brandCode,
            form: this.allGenericForm,
            classification: this.classification,
            subClassification: this.subClassification,
            applyDiscount: this.applyDiscount,
            type: this.type,
            category: this.category,
            genericName: this.allGenericName,
            status: this.status,
            brand: this.brand,
            ingredient: this.ingredient,
            ingredientStatus: this.ingredientStatus,
            description: this.description,
            size: this.size,
            inventoryUOM: this.inventoryUOM,
            purchaseUOM: this.purchaseUOM,
            salesUOMs: this.salesUOMs,
            costInformation: this.suppliers,
            applyVAT: this.applyVAT,
            inventory: this.inventory,
            storage: this.storage,
            regNo: this.Nafdac
        };
   }
   async apply() {
    this.loading = true;
    if (this.id) await this.updateProduct();
    else await this.createProductInventory();
    this.loading = false;
  }
  async createProductInventory() {
    try {
      const response = await cornieClient().post(
        "/api/v1/catalogue-product",
        this.payload
      );
      if (response.success) {
        window.notify({
          msg: "Catalogue product created",
          status: "success",
        });
         this.$router.go(-1);
      }
    } catch (error:any) {
      window.notify({
        msg: error.response.data.message,
        status: "error",
      });
    }
  }
  async updateProduct() {
    const url = `/api/v1/catalogue-product/${this.id}`;
    const payload = {
      ...this.payload,
    };
    try {
      const response = await cornieClient().put(url, payload);
      if (response.success) {
        window.notify({ msg: "Catalogue product  updated", status: "success" });
       this.$router.go(-1);
      }
    } catch (error:any) {
      window.notify({ msg: error.response.data.message, status: "error" });
    }
  }



  async onSave() {
    try {
      this.loading = true;
      if (this.img?.url) {
        this.reqBody.image = this.img.url;
      }
      this.reqBody.costInformation = this.suppliers.map((i:any) => {
        i.type = this.purchaseType;
        return i;
      });

      this.reqBody.salesUOMs = this.sales;
      const created = await this.createProduct(this.reqBody);

      if (created) {
        window.notify({
          msg: `Prodcut ${this.reqBody?.id ? "updated" : "saved"} successfully`,
          status: "success",
        });
        this.$router.go(-1);
      } else {
        window.notify({
          msg: "There was an error, please check the form and try again",
          status: "error",
        });
      }
      this.loading = false;
    } catch (error) {
      this.loading = false;
      window.notify({
        msg: "There was an error, please check the form and try again",
        status: "error",
      });
    }
  }

  setDefault(val: any) {
    this.suppliers.forEach((item: any) => (item.default = false));

    this.suppliers.forEach((item: any) => {
      if (item.id === val) item.default = true;
    });
  }

  SUC = 1000;
  PercentageMarkup = 200;
  MaxDiscount = 10;

  get isRoot() {
    let isRoot = Boolean(
      this.organizationInfo?.rootUserId === this.cornieUser?.id
    );

    return isRoot;
  }
  get CDM() {
    return this.SUC * (this.PercentageMarkup / 100);
  }

  get minimumPrice() {
    return Math.abs(this.CDM * (1 - this.MaxDiscount));
  }

  locationId = null;

  async fetchMarkups() {
    if (this.isRoot) {
      const markups = await cornieClient().get("/api/v1/markup-discount");
      const response = await Promise.all([markups]);
      this.markups = response[0].data as any;

      this.MaxDiscount = this.markups[0]?.maxAllowedDiscount;
      this.PercentageMarkup = this.markups[0]?.markupPercentage;
    } else {
      if (!this.locationId) return [];
      const markups = await cornieClient().get(
        `/api/v1/markup-discount/location/${this.locationId}`
      );
      const response = await Promise.all([markups]);

      this.markups = response[0].data;

      this.MaxDiscount = this.markups[0]?.maxAllowedDiscount;
      this.PercentageMarkup = this.markups[0]?.markupPercentage;
    }

    this.sales.forEach(
      (item: any) => (item.markup = this.PercentageMarkup || 200)
    );
  }

  // get markupItems() {
  //   const markups = this.locations.map((loc: any) => {
  //     let cdm = this.SUC * (this.markups?.markupPercentage / 100);
  //     let margin = Math.abs(cdm - this.SUC);
  //     let percentageMargin = (margin / cdm) * 100;
  //     let minimumPrice = Math.abs(cdm * (1 - this.markups?.maxAllowedDiscount));
  //     let discountMargin = Math.abs(minimumPrice - this.SUC);
  //     let discountMarginPercentage = Math.floor(
  //       (discountMargin / minimumPrice) * 100
  //     );

  //     return {
  //       location: loc.name,
  //       sampleUnitCost: this.SUC,
  //       markupPercentage: this.markups?.markupPercentage,
  //       cdmPrice: cdm,
  //       margin: margin,
  //       marginPercentage: percentageMargin,
  //       maxAllowedDiscount: this.markups?.maxAllowedDiscount,
  //       minPrice: minimumPrice,
  //       discountedMargin: discountMargin,
  //       discountedMarginPercentage: discountMarginPercentage,
  //     };
  //   });

  //   return markups;
  // }

  async fetchLocation() {
    const AllLocation = cornieClient().get(
      "/api/v1/location/myOrg/getMyOrgLocations"
    );

    const response = await Promise.all([AllLocation]);

    if (!this.isRoot) {
      if (!this.locationId) return [];

      response[0].data.forEach((item: any) => {
        if (item.id === this.locationId) {
          this.locations = [item];
        }
      });
    } else {
      this.locations = response[0].data;
    }
  }

   get allName() {
        if (!this.searchresult || this.searchresult.length === 0) return [];
        return this.searchresult.map((i: any) => {
        return {
            code: i.id,
            value: i.id,
            display: i.name,
        };
        });
    }

    get allBrand(){
       if (!this.fullInfo || this.fullInfo.length === 0) return [];
        return this.fullInfo.map((i: any) => {
        return {
            code: i.id,
            value: i.id,
            display: i.name,
        };
        });
    }
 
  get allForms() {
    if (!this.fullBrand || this.fullBrand.length === 0) return [];
    return this.fullInfo.map((i: any) => {
      return {
        code: i.id,
        value: i.id,
        display: i.form,
      };
    });
  }
 

    async searchData(event:any){
        const AllNotes = cornieClient().get(
        `/api/v1/emdex/generic-by-keyword/`,
        {
            keyword : event.target.value,
        }
        );
        const response = await Promise.all([AllNotes]);
        if(response[0].data === 0){
            this.searchresult = 'No medication code found'
        }else{

            this.searchresult = response[0].data;
        }
  }

   async resultData(id:any){
        const AllNotes = cornieClient().get(
        `/api/v1/emdex/generic-brands/${id}`,
        );
        const response = await Promise.all([AllNotes]);
        if(response[0].data === 0){
            this.fullInfo = 'No medication code found'
        }else{

            this.fullInfo = response[0].data;
        }
  }

  get allGenericName(){
      const pt = this.fullInfo.find((i: any) => i.genericId === this.dataCode);
      return this.genericName = pt ? pt.name : "";
  }
  get allGenericCode(){
      const pt = this.fullInfo.find((i: any) => i.id === this.dataBrand);
      return this.genericCode = pt ? pt.name : "";
  }
  get allGenericForm(){
      const pt = this.fullInfo.find((i: any) => i.id === this.dataForm);
      return this.form = pt ? pt.form : "";
  }
  async resultBrand(id:any){
      const pt = this.fullInfo.find((i: any) => i.id === id);
      return this.fullBrand = pt ? pt.form : {};
  }
  async resultPack(id:any){
    console.log(id,"NAFADAC dataCode");
      const pt = this.fullInfo.find((i: any) => i.id === id);
       this.resultStrength(id);
      return this.pack = pt ? `${pt?.pack}` : "Pack not available";
  }

  async resultStrength(id:any){
      const pt = this.fullInfo.find((i: any) => i.id === id);
      this.resultNadac(id);
      return this.strength = pt ? `${pt?.strength}` : "Strength not available";
  }
  async resultNadac(id:any){
      const pt = this.fullInfo.find((i: any) => i.id === id);
      return this.Nafdac = pt ? `${pt?.NAFDAC}` : "NAFDAC not available";
  }

  async created() {
    await this.setProducts();
    if (!this.organizationInfo) await this.fetchOrgInfo();

    await this.fetchMarkups();
    await this.fetchPracticeforms();

    if (!this.isRoot) {
      if (!this.practitioners.length) await this.fetchPractitioners();
      let currentPractiotioner = this.practitioners.find(
        (item: any) => item?.userId === this.cornieUser?.id
      );

      currentPractiotioner?.locationRoles?.forEach((item: any) => {
        if (!item.default) {
          this.locationId = item.locationId;
        }
      });
    }
    await this.fetchLocation();

    if (this.locations?.length <= 0) await this.fetchLocations();
  }
}
</script>

<style scoped>
.v-xteristics {
  font-style: normal;
  font-weight: 600;
  font-size: 14px;
  line-height: 21px;
  color: #fe4d3c;
}

.stock {
  background: #ffffff;
  /* Buttons & Cards */
  box-shadow: 0px 1px 2px rgba(46, 41, 78, 0.02),
    0px 4px 8px rgba(46, 41, 78, 0.08);
  border-radius: 8px;
}

.sub-header {
  font-style: normal;
  font-weight: bold;
  font-size: 18px;
  line-height: 22px;
  color: #14171f;
}

.th {
  font-style: normal;
  font-weight: bold;
  font-size: 12px;
  line-height: 19px;
  letter-spacing: 0.02em;
  text-transform: uppercase;
  color: #080056;
  min-width: 120px;
  width: 16.6%;
  padding: 0.55rem 0.25rem;
}

.ths {
  background: #f0f4fe;
  border-radius: 8px 8px 0px 0px;
  padding: 0.25rem;
}

.tbs {
  background: #ffffff;
  border: 1px solid #c2c7d6;
  box-sizing: border-box;
  border-radius: 0px 0px 8px 8px;
}

.small-text {
  font-style: normal;
  font-weight: normal;
  font-size: 14px;
  line-height: 20px;
  color: #14171f;
}

.sales-value {
  font-style: normal;
  font-weight: bold;
  font-size: 18px;
  line-height: 27px;
  color: #141f15;
}

.sales-label {
  font-style: normal;
  font-weight: normal;
  font-size: 14px;
  line-height: 20px;
  color: #667499;
}

.small-text {
  font-style: normal;
  font-weight: normal;
  font-size: 14px;
  line-height: 20px;
  color: #14171f;
}

input[type="checkbox"]:after {
  border: 1px solid #c4bdbd !important;
}
input[type="checkbox"]:checked:after {
  background-color: #ff0000 !important;
}
</style>
