<template>
  <cornie-dialog v-model="show" right class="w-6/12 h-full">
    <cornie-card height="100%" class="flex flex-col">
      <cornie-card-title class="w-full">
        <cornie-icon-btn @click="show = false" class="">
          <arrow-left-icon />
        </cornie-icon-btn>
        <div class="w-full border-l-2 border-gray-100">
          <h2 class="font-bold float-left text-lg text-primary ml-3 -mt-1">
            {{ newaction }} a Care Team
          </h2>
          <cancel-icon
            class="float-right cursor-pointer"
            @click="show = false"
          />
        </div>
      </cornie-card-title>

      <cornie-card-text class="flex-grow scrollable">
        <v-form>
          <div class="border-b-2 pb-5 border-dashed border-gray-200">
            <accordion-component title="Basic Info" :opened="true">
              <div class="w-full grid grid-cols-2 gap-4 mt-4">
                <cornie-input
                v-if="id"
                  :label="'Identifier'"
                  v-model="identifier"
                  placeholder="--Autogenerated--"
                  :disabled="true"
                >
                </cornie-input>
                <cornie-select
                v-if="id"
                  :rules="required"
                  :items="['active', 'inactive']"
                  v-model="status"
                  label="Status"
                  placeholder="Select"
                >
                </cornie-select>
                <auto-complete
                  :rules="required"
                  :items="dropdowns.category"
                  v-model="category"
                  label="Category"
                  placeholder="Select"
                >
                </auto-complete>
                <!-- <fhir-input
                        reference="http://hl7.org/fhir/ValueSet/care-team-category"
                        class="w-full"
                       v-model="category"
                        label="Category"
                        placeholder="Select"
                      /> -->

                <cornie-input
                  :label="'Name'"
                  v-model="name"
                  placeholder="Enter"
                >
                </cornie-input>
                <cornie-select
                  :rules="required"
                  :items="['Patient', 'Group']"
                  v-model="basedOn"
                  label="subject"
                  placeholder="--Enter--"
                >
                </cornie-select>
                <cornie-select
                  v-if="basedOn == 'Patient'"
                  :items="allPatients"
                  v-model="subjectpatient"
                  label="Patient"
                  placeholder="--Select Patient--"
                >
                </cornie-select>
                <cornie-select
                v-else-if="basedOn == 'Group'"
                  :items="allGroups"
                  v-model="subjectgroup"
                  label="Group"
                  placeholder="--Select group--"
                >
                </cornie-select>
                <d-range-picker
                  :rules="required"
                  v-model="period"
                  label="Period"
                  class="w-full"
                >
                </d-range-picker>
              </div>
            </accordion-component>
          </div>
          <div class="border-b-2 pb-5 border-dashed border-gray-200">
            <accordion-component title="Participants" :opened="false">
              <add-actor @update-actors-list="actorslist" />
              <div class="grid grid-cols-3 gap-4 mt-4">
                <div
                  class="border-r-2"
                  v-for="(item, index) in Actors"
                  :key="index"
                >
                  <div class="mb-8">
                    <div class="flex space-x-4">
                      <avatar
                        class="mr-2 h-14 w-14"
                        v-if="
                          item?.image ||
                          item?.practitioner?.image ||
                          item?.device?.image
                        "
                        :src="
                          item?.image ||
                          item?.practitioner?.image ||
                          item?.device?.image
                        "
                      />
                      <avatar class="mr-2" v-else :src="localSrc" />
                      <div>
                        <p class="text-sm mb-1 text-dark font-semibold">
                          {{
                            item?.name ||
                            item?.practitioner?.firstName +
                              "" +
                              item?.practitioner?.lastName ||
                            item?.device?.name
                          }}
                          <span class="text-gray-500 text-sm">
                            {{
                              item?.job || item?.practitioner?.jobDesignation
                            }}</span
                          >
                        </p>
                        <p class="text-sm text-gray font-light">
                          {{ item?.type }}
                        </p>
                        <!-- <p
                          class="text-sm text-gray font-light"
                          v-if="item.practitioner"
                        >
                          Practitioner
                        </p>
                        <p class="text-sm text-gray font-light" v-else>
                          Device
                        </p> -->
                      </div>
                    </div>
                    <span>
                      <deleteorange-icon
                        class="
                          float-right
                          cursor-pointer
                          relative
                          bottom-8
                          mr-4
                        "
                        @click="removeActor(index)"
                      />
                    </span>
                  </div>
                </div>
              </div>
            </accordion-component>
          </div>
          <div class="border-b-2 pb-5 border-dashed border-gray-200">
            <accordion-component title="Other Info" :opened="false">
              <div class="grid grid-cols-2 gap-4 mt-4">
                <fhir-input
                  reference="	http://hl7.org/fhir/ValueSet/clinical-findings"
                  class="w-full"
                  v-model="reasonCode"
                  label="Reason Code"
                  placeholder="Select"
                />
                <div>
                    <p class="text-sm text-black font-semibold mb-1">
                      Reason Reference
                    </p>
                    <div
                      class="flex w-full border-2 border-gray-200 bg-gray-100 rounded-lg py-2 px-4 cursor-pointer"
                      @click="showRefModal = true"
                    >
                      <span class="w-full">{{ reasonReference }}</span>
                      <span class="flex justify-end w-full">
                        <plusIcon class="fill-current text-danger mt-1" />
                      </span>
                    </div>
                  </div>
                <!-- <cornie-input
                  :label="'Reason Reference'"
                  v-model="reasonReference"
                  placeholder="Enter"
                >
                </cornie-input> -->
                <cornie-input
                  :rules="emailRule"
                  :label="'Email Address'"
                  v-model="email"
                  placeholder="Enter"
                >
                </cornie-input>
                <phone-input
                  required
                  class="w-full"
                  label="Phone Number"
                  v-model:code="phone.dialCode"
                  v-model="phone.number"
                  placeholder="--Enter--"
                  :rules="requiredRule"
                />
              </div>
              <div>
                <text-area
                  :label="'Notes'"
                  class="w-full"
                  v-model="note"
                  :placeholder="'Start typing'"
                />
              </div>
            </accordion-component>
          </div>
        </v-form>
      </cornie-card-text>

      <cornie-card>
        <cornie-card-text class="flex justify-end">
          <cornie-btn
            @click="show = false"
            class="border-primary border-2 mr-3 rounded-xl text-primary"
          >
            Cancel
          </cornie-btn>
          <cornie-btn
            :loading="loading"
            @click="submit"
            class="text-white bg-danger px-2 rounded-xl"
          >
            Save
          </cornie-btn>
        </cornie-card-text>
      </cornie-card>
    </cornie-card>
  </cornie-dialog>
  <reference-modal v-model="showRefModal" @ref-value="refvalue"/>
</template>

<script lang="ts">
import { cornieClient } from "@/plugins/http";
import search from "@/plugins/search";
import { string } from "yup";
import { Options, Vue, setup } from "vue-class-component";
import { Prop, PropSync, Watch } from "vue-property-decorator";
import { namespace } from "vuex-class";
import { mapDisplay } from "@/plugins/definitions";

import ICareteam, { Participants } from "@/types/ICareteam";
import IGroup from "@/types/IGroup";
import { IPatient } from "@/types/IPatient";

import AccordionComponent from "@/components/form-accordion.vue";
import CornieCard from "@/components/cornie-card";
import CornieIconBtn from "@/components/CornieIconBtn.vue";
import ArrowLeftIcon from "@/components/icons/arrowleft.vue";
import CornieDialog from "@/components/CornieDialog.vue";
import CornieBtn from "@/components/CornieBtn.vue";
import IconInput from "@/components/IconInput.vue";
import SearchIcon from "@/components/icons/search.vue";
import CancelIcon from "@/components/icons/CloseIcon.vue";
import CloseIcon from "@/components/icons/whitecancel.vue";
import CornieSelect from "@/components/cornieselect.vue";
import Avatar from "@/components/avatar.vue";
import DeleteIcon from "@/components/icons/delete.vue";
import SelectOption from "@/components/custom-checkbox.vue";
import TextArea from "@/components/textarea.vue";
import CornieInput from "@/components/cornieinput.vue";
import DRangePicker from "@/components/daterangecalendar.vue";
import DatePicker from "@/components/datepicker.vue";
import PhoneInput from "@/components/phone-input.vue";
import CornieRadio from "@/components/cornieradio.vue";
import DeleteorangeIcon from "@/components/icons/deleteorange.vue";
import Multiselect from "@vueform/multiselect";
import FhirInput from "@/components/fhir-input.vue";
import AutoComplete from "@/components/autocomplete.vue";
import InfoBlueBg from "@/components/icons/info-blue-bg.vue";
import plusIcon from "@/components/icons/plus.vue";

import ReferenceModal from "./components/referenceModal.vue";
import AddActor from "./actors.vue";

const careteam = namespace("careteam");
const dropdown = namespace("dropdown");
const patients = namespace("patients");
const group = namespace("group");

@Options({
  name: "careTeamModal",
  components: {
    ...CornieCard,
    AccordionComponent,
    CornieIconBtn,
    ArrowLeftIcon,
    InfoBlueBg,
    DRangePicker,
    PhoneInput,
    FhirInput,
    CancelIcon,
    AutoComplete,
    CornieDialog,
    CornieRadio,
    AddActor,
    Avatar,
    SelectOption,
    SearchIcon,
    TextArea,
    DeleteIcon,
    DatePicker,
    Multiselect,
    IconInput,
    CornieInput,
    CornieBtn,
    CornieSelect,
    CloseIcon,
    DeleteorangeIcon,
    ReferenceModal,
    plusIcon
  },
})
export default class careTeamModal extends Vue {
  @PropSync("modelValue", { type: Boolean, default: false })
  show!: boolean;

  @Prop({ type: String, default: "" })
  id!: string;

  @careteam.Action
  getCareteamById!: (id: string) => ICareteam;

  @patients.State
  patients!: IPatient[];

  @patients.Action
  fetchPatients!: () => Promise<void>;

  @group.State
  groups!: IGroup[];

  @group.Action
  fetchGroups!: () => Promise<void>;

  requiredRule = string().required();

  loading = false;
  showRefModal = false;
  DialCode = "+234";
  PhoneNumber = "";

  subjectpatient = "";
  subjectgroup = "";

  identifier = "";
  basedOn = "Patient";
  replaces = "";
  startDateTime = "";
  endDateTime = "";
  startDateTimePeriod = "";
  endDateTimePeriod = "";
  startDateTimeCom = "";
  endDateTimeCom = "";
  startDateCom = "";
  endDateCom = "";
  value = "";
  reasonCode = "";
  reasonReference = "";
  localSrc = require("../../../../assets/img/placeholder.png");
  use = "Home";
  system = "Phone";
  subject = "Patient";
  search = "";
  onBehalfOf = "";
  role = "";
  member = "";
  notes = "";
  data: any = {
    days: [],
  };

  communication = [] as IIndexableObject[];

  dropdowns = {} as IIndexableObject;

  @dropdown.Action
  getDropdowns!: (a: string) => Promise<IIndexableObject>;

  status = "active";
  category = "";
  name = "";
  participants: Participants[] = [];
  period = { start: "", end: "" };
  emailRule = string().email().required();
  required = string().required();
  fax = "";
  Actors = [] as any;

  phone = {
    number: "",
    dialCode: "+234",
  } as any;
  note = "";
  email = "";
  Identifier = "";

  async handleSystemChange(val: string) {
    this.system = val;
    console.log(val);
  }

  async addCommunication() {
    if (
      this.system === "" ||
      this.value === "" ||
      this.use === "" ||
      this.startDateTimeCom === "" ||
      this.endDateTimeCom === ""
    )
      return;

    let info = {
      system: this.system,
      value: this.value,
      use: this.use,
      startDate: new Date(this.startDateTimeCom).toLocaleString(),
      endDate: new Date(this.endDateTimeCom).toLocaleString(),
    } as IIndexableObject;

    this.communication = [info, ...this.communication];
    this.system = "Phone";
    this.use = "Home";

    this.value = this.startDateTimeCom = this.endDateTimeCom = "";
  }

  get activePatientId() {
    const id = this.$route?.params?.id as string;
    return id;
  }

  refvalue(value:any, type:string){
    //this.references.push(value);
    this.reasonReference = type;
  }

  actorslist(value: any) {
    this.Actors = value;
  }
  removeActor(index: number) {
    this.Actors.splice(index, 1);
  }
  @Watch("id")
  idChanged() {
    this.setCareteam();
  }

  async setCareteam() {
    const careteam = await this.getCareteamById(this.id);
    if (!careteam) return;
    this.identifier = careteam.identifier;
    this.status = careteam.status;
    this.category = careteam.category;
    this.name = careteam.name;
    this.subject = careteam.subject;
    this.period = careteam.period;
    this.Actors = careteam.participants;
    this.reasonCode = careteam.reasonCode;
    this.reasonReference = careteam.reasonReference;
    this.note = careteam.note;
    this.phone = careteam.phone;
    this.email = careteam.email;
  }

  get payload() {
    return {
      identifier: this.identifier,
      status: this.status,
      category: this.category,
      name: this.name,
      subject: this.subject,
      period: this.period,
      participants: this.Actors,
      reasonCode: this.reasonCode,
      reasonReference: this.reasonReference,
      note: this.note,
      phone: this.phone,
      email: this.email,
      patientId: this.activePatientId,
    };
  }

  get newaction() {
    return this.id ? "Update" : "Create";
  }

  async submit() {
    this.loading = true;
    if (this.id) await this.updateCareteam();
    else await this.createCareteam();
    this.loading = false;
  }

  async createCareteam() {
    this.payload.period.start = new Date(
      this.payload.period.start
    ).toISOString();
    this.payload.period.end = new Date(this.payload.period.end).toISOString();
   
    try {
      const response = await cornieClient().post(
        "/api/v1/care-teams",
        this.payload
      );
      if (response.success) {
        window.notify({ msg: "Care team added", status: "success" });
        this.done();
      }
    } catch (error: any) {
      window.notify({
        msg: error.response.data.message,
        status: "error",
      });
    }
  }

  async updateCareteam() {
    const url = `/api/v1/care-teams/${this.id}`;
    const payload = { ...this.payload };
    try {
      const response = await cornieClient().put(url, payload);
      if (response.success) {
        window.notify({ msg: "Care team updated", status: "success" });
        this.done();
      }
    } catch (error: any) {
      window.notify({
        msg: error.response.data.message,
        status: "error",
      });
    }
  }

  get allPatients() {
    if (!this.patients || this.patients.length === 0) return [];
    return this.patients.map((i: any) => {
      return {
        code: i.id,
        display: `${i.firstname} ${i.lastname}`,
      };
    });
  }

  get allGroups() {
    if (!this.groups || this.groups.length === 0) return [];
    return this.groups.map((i: any) => {
      return {
        code: i.id,
        display: `${i.name}`,
      };
    });
  }

  async fetchOrgInfo() {
    try {
      const response = await cornieClient().get(
        "/api/v1/organization/myOrg/get"
      );
      this.identifier = response.data.identifier;
    } catch (error) {
      alert("Could not fetch organization");
    }
  }
  done() {
    this.$emit("careteam-added");
    this.show = false;
  }

  async created() {
    await this.setCareteam();
    await this.fetchPatients();
    await this.fetchGroups();
    this.fetchOrgInfo();
    const data = await this.getDropdowns("careTeam");
    this.dropdowns = data;
  }
}
</script>
