<template>
  <cornie-dialog v-model="show" right class="w-8/12 h-full">
    <cornie-card height="100%" class="flex flex-col">
      <cornie-card-title class="w-full">
        <cornie-icon-btn @click="show = false" class="">
                <arrow-left-icon />
        </cornie-icon-btn>
        <div class="w-full border-l-2 border-gray-100">
          <h2 class="font-bold float-left text-lg text-primary ml-3 -mt-1">
          Create a Care Team
          </h2>
          <cancel-icon
            class="float-right cursor-pointer"
            @click="show = false"
          />
        </div>
      </cornie-card-title>

      <cornie-card-text class="flex-grow scrollable">
         <v-form ref="form">
             <div  class="border-b-2 pb-5 border-dashed border-gray-200">
                <accordion-component
                  title="Basic Info"
                  :opened="true"
                >
                <div class="w-full grid grid-cols-2 gap-4 mt-4">
                    <cornie-input
                        :label="'Identifier'"
                        v-model="Identifier"
                        placeholder="--Autogenerated--"
                        :disabled="true"
                    >
                    </cornie-input>
                    <cornie-select
                        :rules="required"
                        :items="['Active', 'Inactive']"
                        v-model="status"
                        label="Status"
                        placeholder="Select"
                    >
                    </cornie-select>
                    <cornie-select
                        :rules="required"
                        :label="'Category'"
                        :items="['Active', 'Inactive']"
                        v-model="category"
                        placeholder="Select"
                    >
                    </cornie-select>
                     <cornie-input
                        :label="'Name'"
                        v-model="name"
                        placeholder="Enter"
                    >
                    </cornie-input>   
                    <cornie-select
                        :rules="required"
                        :items="['Active', 'Inactive']"
                        v-model="basedOn"
                        label="sUBJECT"
                        placeholder="--Enter--"
                    >
                    </cornie-select>
                    <d-range-picker
                        :rules="required"
                        v-model="period"
                        label="Period"
                        class="w-full"
                      >
                    </d-range-picker>
                </div>
                </accordion-component>
             </div>
            <div  class="border-b-2 pb-5 border-dashed border-gray-200">
                <accordion-component title="Participants" :opened="false">
                <add-actor @update-actors-list="actorslist"/>
                  <div class="grid grid-cols-3 gap-4 mt-4">
                      <div
                        class="border-r-2"
                        v-for="(item, index) in Actors"
                        :key="index"
                      >
                        <div class="mb-8">
                          <div class="flex space-x-4">
                            <avatar
                              class="mr-2 h-14 w-14"
                              v-if="item?.image"
                              :src="item?.image"
                            />
                            <avatar
                              class="mr-2"
                              v-else
                              :src="localSrc"
                            />
                            <div>
                              <p class="text-sm mb-1 text-dark font-semibold">
                              {{ item?.name }}
                              <span class="text-gray-500 text-sm"> {{ item?.job }}</span>
                              </p>
                              <p class="text-sm text-gray font-light">
                                {{ item.type }}
                              </p>
                            </div>
                          </div>
                          <span>
                            <deleteorange-icon
                              class="float-right cursor-pointer relative bottom-8 mr-4"
                              @click="removeActor(index)"
                            />
                          </span>
                        </div>
                      </div>
                  </div>
                </accordion-component>
            </div>
            <div  class="border-b-2 pb-5 border-dashed border-gray-200">
                <accordion-component title="Other Info" :opened="false">
                  <div class="grid grid-cols-2 gap-4 mt-4">
                     <cornie-select
                        :rules="required"
                        :items="['Active', 'Inactive']"
                        v-model="reasonCode"
                        label="Reason Code"
                        placeholder="Select"
                    >
                    </cornie-select>
                      <cornie-input
                          :label="'Reason Reference'"
                          v-model="reasonReference"
                          placeholder="Enter"
                      >
                      </cornie-input>
                       <cornie-input
                        :rules="required"
                          :label="'Email Address *'"
                          v-model="email"
                          placeholder="Enter"
                      >
                      </cornie-input>
                       <phone-input
                          required
                          class="w-full"
                          label="Phone Number"
                          v-model:code="phone.dialCode"
                          v-model="phone.number"
                          placeholder="--Enter--"
                          :rules="requiredRule"
                        />
                  </div>
                  <div>
                    <text-area :label="'Notes'" class="w-full" v-model="note" :placeholder="'Start typing'"/>
                  </div>
                </accordion-component>
            </div>


        </v-form>
      </cornie-card-text>
      
      <cornie-card>
        <cornie-card-text class="flex justify-end">
          <cornie-btn
            @click="show = false"
            class="border-primary border-2  mr-3 rounded-xl text-primary"
          >
            Cancel
          </cornie-btn>
          <cornie-btn
            :loading="loading"
             @click="submit"
            class="text-white bg-danger px-2 rounded-xl"
           >
            Save
          </cornie-btn>

        </cornie-card-text>
      </cornie-card>
    </cornie-card>


  </cornie-dialog>
</template>

<script lang="ts">
import { cornieClient } from "@/plugins/http";
import search from "@/plugins/search";
import { string } from "yup";
import { Options, Vue, setup } from "vue-class-component";
import { Prop, PropSync, Watch } from "vue-property-decorator";
import { namespace } from "vuex-class";
import { mapDisplay } from "@/plugins/definitions";


import ICareteam, { Participants } from "@/types/ICareteam";
import IRequest, { Medications, RefillSection } from "@/types/IRequest";


import AccordionComponent from "@/components/form-accordion.vue";
import CornieCard from "@/components/cornie-card";
import CornieIconBtn from "@/components/CornieIconBtn.vue";
import ArrowLeftIcon from "@/components/icons/arrowleft.vue";
import CornieDialog from "@/components/CornieDialog.vue";
import CornieBtn from "@/components/CornieBtn.vue";
import IconInput from "@/components/IconInput.vue";
import SearchIcon from "@/components/icons/search.vue";
import CancelIcon from "@/components/icons/CloseIcon.vue";
import CloseIcon from "@/components/icons/whitecancel.vue";
import CornieSelect from "@/components/cornieselect.vue";
import Avatar from "@/components/avatar.vue";
import DeleteIcon from "@/components/icons/delete.vue";
import SelectOption from "@/components/custom-checkbox.vue";
import TextArea from "@/components/textarea.vue";
import CornieInput from "@/components/cornieinput.vue";
import DRangePicker from "@/components/daterangecalendar.vue";
import DatePicker from "@/components/datepicker.vue";
import PhoneInput from "@/components/phone-input.vue";
import CornieRadio from "@/components/cornieradio.vue";
import DeleteorangeIcon from "@/components/icons/deleteorange.vue";
import Multiselect from "@vueform/multiselect";
import FhirInput from "@/components/fhir-input.vue";
import AutoComplete from "@/components/autocomplete.vue";
import InfoBlueBg from "@/components/icons/info-blue-bg.vue";

import AddActor from "./actors.vue";




const careteam = namespace("careteam");
const dropdown = namespace("dropdown");

const emptyParticipant: Participants = {
  name: "",
  role: "",
  onBehalfOf: "",
  period: { start: "2011/12/15", end: "2017/12/19" },
  reasonCode: "",
  reasonReference: "",
  managingOrganization: "",
  phone: { number: "", dialCode: "" },
  email: "",
  notes: "",
};

@Options({
  name: "careTeamModal",
  components: {
    ...CornieCard,
    AccordionComponent,
    CornieIconBtn,
    ArrowLeftIcon,
    InfoBlueBg,
    DRangePicker,
    PhoneInput,
    FhirInput,
    CancelIcon,
    AutoComplete,
    CornieDialog,
    CornieRadio,
    AddActor,
    Avatar,
    SelectOption,
    SearchIcon,
    TextArea,
    DeleteIcon,
    DatePicker,
    Multiselect,
    IconInput,
     CornieInput,
    CornieBtn,
    CornieSelect,
    CloseIcon,
    DeleteorangeIcon
  },
})
export default class careTeamModal extends Vue {
    @PropSync("modelValue", { type: Boolean, default: false })
    show!: boolean;

    @Prop({ type: String, default: "" })
    id!: string;

    
  @careteam.Action
  getCareteamById!: (id: string) => ICareteam;

  requiredRule = string().required();

   loading = false;
    DialCode = "+234";
    PhoneNumber = "";

  identifier = "";
  basedOn = "";
  replaces = "";
  startDateTime = "";
  endDateTime = "";
  startDateTimePeriod = "";
  endDateTimePeriod = "";
  startDateTimeCom = "";
  endDateTimeCom = "";
    startDateCom = "";
  endDateCom = "";
  value = "";
  reasonCode = "";
  reasonReference = "";
  localSrc = require("../../../../assets/img/placeholder.png");
  use = "Home";
  system = "Phone";
  subject = "Patient";
  search = "";
  onBehalfOf = "";
  role = "";
  member = "";
  notes = "";
   data: any = {
    days: [],
  };

  communication = [] as IIndexableObject[];
  
  dropdowns = {} as IIndexableObject;

  @dropdown.Action
  getDropdowns!: (a: string) => Promise<IIndexableObject>;

  status = "";
  category = "";
  name = "";
  participant = { ...emptyParticipant };
  participants: Participants[] = [];
  period = { start: "2011/09/12", end: "2011/12/19" };
  required = string().required();
  fax = "";
  Actors = [];

  phone = {
    number: "",
    dialCode: ""
  };
  note = "";
  email = "";
  Identifier = "";
  


 async handleSystemChange(val: string) {
    this.system = val;
    console.log(val);
  }

   async addCommunication() {
    if (
      this.system === "" ||
      this.value === "" ||
      this.use === "" ||
      this.startDateTimeCom === "" ||
      this.endDateTimeCom === ""
    )
      return;

    let info = {
      system: this.system,
      value: this.value,
      use: this.use,
      startDate: new Date(this.startDateTimeCom).toLocaleString(),
      endDate: new Date(this.endDateTimeCom).toLocaleString(),
    } as IIndexableObject;

    this.communication = [info, ...this.communication];
    this.system = "Phone";
    this.use = "Home";

    this.value = this.startDateTimeCom = this.endDateTimeCom = "";
  }

  actorslist(value:any){
    this.Actors = value;
  }
   removeActor(index: number) {
    this.Actors.splice(index, 1);
  }
    @Watch("id")
    idChanged() {
      this.setCareteam();
    }


    async setCareteam() {
        const careteam = await this.getCareteamById(this.id);
        if (!careteam) return;
        this.identifier = careteam.identifier;
        this.status = careteam.status;
        this.category = careteam.category;
        this.name = careteam.name;
        this.subject = careteam.subject;
        this.period = careteam.period;
        this.participants = careteam.participants;
  }
  
  

    get payload() {
        return {
            identifier: this.identifier,
            status: this.status,
            category: this.category,
            name: this.name,
            subject: this.subject,
            period: this.period,
            participants: this.participants,
        
        };
   }

      async checkParticipant() {
    this.loading = true;
    if (this.id) await this.updateParticipant();
    else await this.addParticipant();
    this.loading = false;
  }
  async editParticipant(id: string, index: number, fieldType: object) {
    this.participant = this.participants[index];
  }
  async updateParticipant() {
    const url = `/api/v1/participants/${this.id}`;
    const payload = { ...this.participant };
    try {
      const response = await cornieClient().put(url, payload);
      if (response.success) {
        window.notify({ msg: "Participant updated", status: "success" });
      }
    } catch (error) {
      window.notify({ msg: "Participant not updated", status: "error" });
    }
  }
  async addParticipant() {
    if (!this.id) {
      this.participants.push({ ...this.participant });
      this.reset();
      window.notify({ msg: "Participant added", status: "success" });
      return;
    }
    //  this.participant.careTeamId = this.id;
    try {
      const response = await cornieClient().post(
        "/api/v1/participants",
        this.participant
      );
      if (response.success) {
        this.participants.push(response.data);
        window.notify({ msg: "Participant added", status: "success" });
        this.reset();
      }
    } catch (error) {
      window.notify({ msg: "Participant  not added", status: "error" });
    }
  }

  async reset() {
    this.participant = { ...emptyParticipant };
  }
  async removeParticipant(id: string, index: number, fieldType: object) {
    this.participants.splice(index, 1);
    window.notify({ msg: "Participant deleted", status: "success" });
    //  try {
    // const response = await cornieClient().delete(`/api/v1/participants/${id}`);
    // if (response.success) {
    //     this.participants.splice(index, 1);
    //     window.notify({ msg: "Participant deleted", status: "success" });
    // }
    // } catch (error) {
    //   window.notify({ msg: "Participant not deleted", status: "error" });
    // }
  }



   async submit() {
    this.loading = true;
    if (this.id) await this.updateCareteam();
    else await this.createCareteam();
    this.loading = false;
  }

  async createCareteam() {
    this.payload.period.start = new Date(
      this.payload.period.start
    ).toISOString();
    this.payload.period.end = new Date(this.payload.period.end).toISOString();
    this.participant.period.start = new Date(
      this.participant.period.start
    ).toISOString();
    this.participant.period.end = new Date(
      this.participant.period.end
    ).toISOString();
    try {
      const response = await cornieClient().post(
        "/api/v1/care-teams",
        this.payload
      );
      if (response.success) {
        window.notify({ msg: "Care team added", status: "success" });
      }
    } catch (error) {
      window.notify({ msg: "Care team  not added", status: "error" });
    }
  }

  async updateCareteam() {
    const url = `/api/v1/care-teams/${this.id}`;
    const payload = { ...this.payload };
    try {
      const response = await cornieClient().put(url, payload);
      if (response.success) {
        window.notify({ msg: "Care team updated", status: "success" });
      }
    } catch (error) {
      window.notify({ msg: "Care team not updated", status: "error" });
    }
  }

     async fetchOrgInfo() {
    try {
      const response = await cornieClient().get(
        "/api/v1/organization/myOrg/get"
      );
      this.identifier = response.data.identifier;
      this.participant.managingOrganization = response.data.name;
    } catch (error) {
      alert("Could not fetch organization");
    }
  }
  done() {
        this.$emit("medication-added");
        this.show = false;
  }

  async created() {
     this.setCareteam();
    this.fetchOrgInfo();
    const data = await this.getDropdowns("careTeam");
    this.dropdowns = data;

  }
}
</script>
