<template>
  <cornie-dialog v-model="show" right class="w-4/12 h-full">
    <cornie-card height="100%" class="flex flex-col">
      <cornie-card-title class="w-full">
        <span class="pr-2 flex items-center cursor-pointer border-r-2">
          <cornie-icon-btn @click="show = false">
            <arrow-left-icon />
          </cornie-icon-btn>
        </span>
        <div class="w-full">
          <h2 class="font-bold float-left text-lg text-primary ml-3 -mt-1">
            Add Item
          </h2>
          <cancel-icon
            class="float-right cursor-pointer"
            @click="show = false"
          />
        </div>
      </cornie-card-title>

      <cornie-card-text class="flex-grow scrollable">
        <div>
          <search-input
            placeholder="--Search products--"
            v-model="query"
            :results="results"
            @selected="selected"
          />

          <v-form ref="form" class="mt-5">
            <cornie-input
              label="Item Code"
              class="w-full mb-5"
              placeholder="--Autogenerated--"
              v-model="supply.itemCode"
            />
            <cornie-input
              label="Item Name"
              class="w-full mb-5"
              placeholder="--Autogenerated--"
              v-model="supply.itemName"
            />
            <cornie-input
              label="Brand"
              class="w-full mb-5"
              v-model="supply.brand"
              placeholder="--Autogenerated--"
            />
            <cornie-input
              label="Form"
              class="w-full mb-5"
              placeholder="--Autogenerated--"
              v-model="supply.form"
            />
            <cornie-input
              label="Strength"
              class="w-full mb-5"
              placeholder="--Enter--"
              v-model="supply.strength"
            />
            <auto-complete
              :label="'Batch #'"
              :items="allBatch"
              @input="searchBatch"
              @click="resultData(supply.batchNumber)"
              v-model="supply.batchNumber"
              :placeholder="'Search batch number'"
            />

            <date-picker
              label="Expiry"
              class="w-full mb-5"
              placeholder="--Autogenerated--"
              v-model="supply.exipry"
              :disabled="true"
            />
            <cornie-input
              label="UoM"
              class="w-full mt-5"
              placeholder="--Enter--"
              v-model="supply.uofm"
            />
            <cornie-input
              label="Pack Size"
              class="w-full mb-5 mt-4"
              placeholder="--Enter--"
              v-model="supply.packSize"
            />
          </v-form>
        </div>
      </cornie-card-text>

      <cornie-card>
        <cornie-card-text class="flex justify-end">
          <cornie-btn
            @click="show = false"
            class="border-primary border-2 px-6 mr-3 rounded-xl text-primary"
          >
            Cancel
          </cornie-btn>
          <cornie-btn
            :loading="loading"
            @click="apply"
            class="text-white bg-danger px-6 rounded-xl"
          >
            Save
          </cornie-btn>
        </cornie-card-text>
      </cornie-card>
    </cornie-card>
  </cornie-dialog>
</template>

<script lang="ts">
import { Vue, Options } from "vue-class-component";
import { Prop, PropSync, Watch } from "vue-property-decorator";
import { namespace } from "vuex-class";
import { cornieClient } from "@/plugins/http";

import ICatalogueService, { ICatalogueProduct } from "@/types/ICatalogue";

import CornieCard from "@/components/cornie-card";
import Textarea from "@/components/textarea.vue";
import CornieIconBtn from "@/components/CornieIconBtn.vue";
import ArrowLeftIcon from "@/components/icons/arrowleft.vue";
import CornieRadio from "@/components/cornieradio.vue";
import CornieDialog from "@/components/CornieDialog.vue";
import InfoIcon from "@/components/icons/info.vue";
import CornieInput from "@/components/cornieinput.vue";
import CornieSelect from "@/components/autocomplete.vue";
import MainCornieSelect from "@/components/cornieselect.vue";
import CorniePhoneInput from "@/components/phone-input.vue";
import CornieBtn from "@/components/CornieBtn.vue";
import NoteIcon from "@/components/icons/graynote.vue";
import DEdit from "@/components/icons/aedit.vue";
import RangeSlider from "@/components/range.vue";
import CDelete from "@/components/icons/adelete.vue";
import IconInput from "@/components/IconInput.vue";
import SearchIcon from "@/components/icons/search.vue";
import AccordionComponent from "@/components/dialog-accordion.vue";
import CancelIcon from "@/components/icons/CloseIcon.vue";
import SearchInput from "@/components/search-input.vue";
import DatePicker from "@/components/datepicker.vue";
import AutoComplete from "@/components/autocomplete.vue";


const catalogue = namespace("catalogues");
const user = namespace("user");

interface Result extends ICatalogueProduct {
  display: string;
}

@Options({
  name: "itemModal",
  components: {
    ...CornieCard,
    CornieIconBtn,
    NoteIcon,
    ArrowLeftIcon,
    RangeSlider,
    DEdit,
    CDelete,
    CancelIcon,
    InfoIcon,
    CornieDialog,
    SearchIcon,
    AccordionComponent,
    IconInput,
    Textarea,
    CornieInput,
    CornieSelect,
    CorniePhoneInput,
    CornieRadio,
    CornieBtn,
    MainCornieSelect,
    SearchInput,
    DatePicker,
    AutoComplete,
  },
})
export default class itemModal extends Vue {
  @PropSync("modelValue", { type: Boolean, default: false })
  show!: boolean;

  @Prop({ type: String, default: "" })
  id!: string;

  @Prop({ type: String, default: "" })
  supplierName!: string;

  loading = false;

  @user.Getter
  authCurrentLocation!: string;

  avQty = 0;
  itemName = "";
  itemCode = "";
  expiryDate = "";
  quantity = 0;
  packSize = "";
  uofm = "";
  strength = "";
  form = "";
  brand = "";


  query = "";
  results: Result[] = [];
  searchresult = [] as any;

  supply = {
    productId: "",
    itemName: "",
    itemCode: "",
    brand: "",
    form: "",
    strength: "",
    batchNumber: "",
    expiry: "",
    uom: "",
    packSize: "",
    unitCost: 0,
    referenceqty: 0,
    quantity: 0,
  } as any;

  inventoryProducts = [] as any;

  @Watch("query")
  async search(query: string) {
    if (!query) return (this.results = []);
    const inventoryProducts = await this.fetchInventoryProduct(query);
    this.results = this.inventoryProducts.map((p: any) => ({
      ...p,
      display: this.printProduct(p),
    }));
  }

  printProduct(product: any) {
    return `${product.itemName}`;
  }

  async selected(product: any) {
    this.supply.productId = product.productId;
    this.supply.itemName = product.itemName;
    this.supply.itemCode = product.itemCode;
    this.supply.brand = product.brand;
    this.supply.form = product.form;
    this.supply.batchNumber = product.batchNumber;
    this.supply.form = product.form;
    this.supply.expiry = product.expiry;
    this.supply.uom = product.uofm || "";
    this.supply.packSize = product.packSize;
    this.supply.strength = product.strength || "unknown";
    this.supply.referenceqty = product.availableQuantity;
  }

  async apply() {
    this.supply.quantity = this.quantity;
    this.supply.expiryDate = this.expiryDate;
    this.supply.supplier = this.supplierName;

    this.loading = true;
    this.$emit("item-supplier", this.supply);

    this.show = false;
    this.loading = false;
    this.supply = {};
    this.supply.productId = "";
    this.supply.itemName = "";
    this.supply.itemCode = "";
    this.supply.brand = "";
    this.supply.form = "";
    this.supply.batchNumber = "";
    this.supply.form = "";
    this.supply.expiry = "";
    this.supply.uom = "";
    this.supply.packSize = "";
    this.query = "";
  }

  async fetchInventoryProduct(query: string) {
    const AllLocation = cornieClient().get(
      `/api/v1/inventory/product/search/${this.authCurrentLocation}`,
      { query }
    );
    const response = await Promise.all([AllLocation]);
    this.inventoryProducts = response[0].data;
  }
   async searchBatch(event: any) {
    const AllNotes = cornieClient().get(
      `/api/v1/inventory/product/batch/${this.authCurrentLocation}/${this.supply.productId}`,
      {
        query: event.target.value,
      }
    );
    const response = await Promise.all([AllNotes]);
    if (response[0].data === 0) {
     return  "No batch number found";
    } else {
      this.searchresult = response[0].data;
    }
  }

   get allBatch() {
        if (!this.searchresult || this.searchresult.length === 0) return [];
        return this.searchresult.map((i: any) => {
        return {
            code: i.batchNumber,
            display: i.batchNumber ?? 'No batch number found',
        };
        });
    } 

  async resultData(code: string) {
    const pt = this.searchresult.find((i: any) => i.batchNumber === code);
    return this.supply.exipry = pt ? `${pt.expiryDate}` : "";
  }
  async created() {}
}
</script>

<style></style>
