<template>
  <button
    :disabled="loading || disabled"
    class="focus:outline-none block"
    :class="{ 'py-1 cursor-wait': loading, ' cursor-not-allowed': disabled }"
  >
    <div class="loadingio-spinner-rolling-pciy0fvd3t mt-auto" v-if="loading">
      <div class="ldio-s45rszdrvn">
        <div></div>
      </div>
    </div>
    <span v-else> <slot /> </span>
  </button>
</template>
<script lang="ts">
import { Options, Vue } from "vue-class-component";
import { Prop } from "vue-property-decorator";

@Options({})
export default class CornieBtn extends Vue {
  @Prop({ type: Boolean, default: false })
  loading!: boolean;

  @Prop({ type: Boolean, default: false })
  disabled!: boolean;
}
</script>

<style type="text/css">
@keyframes ldio-s45rszdrvn {
  0% {
    transform: translate(-50%, -50%) rotate(0deg);
  }
  100% {
    transform: translate(-50%, -50%) rotate(360deg);
  }
}
.ldio-s45rszdrvn div {
  position: absolute;
  width: 62px;
  height: 62px;
  border: 10px solid #e4e8eb;
  border-top-color: transparent;
  border-radius: 50%;
}
.ldio-s45rszdrvn div {
  animation: ldio-s45rszdrvn 1.2048192771084336s linear infinite;
  top: 50px;
  left: 50px;
}
.loadingio-spinner-rolling-pciy0fvd3t {
  width: 31px;
  height: 31px;
  display: inline-block;
  overflow: hidden;
  background: none;
}
.ldio-s45rszdrvn {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(0.31);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-s45rszdrvn div {
  box-sizing: content-box;
}
/* generated by https://loading.io/ */
</style>
